### ISSUE TITLE
Unhanded Exception

### ISSUE THREAD

**Issue by CodyKurr** [TEdit/Terraria-Map-Editor#1016]
## What were you doing when the issue occured?
I Have been trying to install and use Tedit for the past day, and nothing has worked. I have tried reading other threads, updating to Windows 10, reinstalling Terraria through Steam, retrying the installer, and downloading the .Net to its proper update, and nothing has worked. Wherever i click on the TEditXna file to open it, I only get the same error message.
## Can you reproduce the issue?
Yes, every time I try the file or re download it I get the same problem. 
## What version of Terraria are you using?
3.5.5.3
## Post relevant contents of log or attach log file _**(very important)**_:
07-31-2017 01:10:02: Starting TEdit 3.10.17116.2025 
07-31-2017 01:10:02: OS: Microsoft Windows NT 6.2.9200.0 
07-31-2017 01:10:02: Failed to verify Terraria Paths. TEdit may not run properly. 
07-31-2017 01:10:02: Error - Could not load file or assembly 'GalaSoft.MvvmLight, Version=5.3.0.19026, Culture=neutral, PublicKeyToken=e7570ab207bcb616' or one of its dependencies. The system cannot find the file specified.
   at TEditXna.DependencyChecker.CheckPaths()
   at TEditXna.App.OnStartup(StartupEventArgs e) in C:\projects\terraria-map-editor\TEditXna\App.xaml.cs:line 48 
07-31-2017 01:10:02: Unable to locate Terraria. No texture data will be available. 
07-31-2017 01:10:03: Error - Could not load file or assembly 'GalaSoft.MvvmLight, Version=5.3.0.19026, Culture=neutral, PublicKeyToken=e7570ab207bcb616' or one of its dependencies. The system cannot find the file specified.
   at TEditXna.MainWindow..ctor() 
07-31-2017 01:10:03: Error - The invocation of the constructor on type 'TEditXna.MainWindow' that matches the specified binding constraints threw an exception.
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at TEditXna.App.Main()

**Comment by BinaryConstruct** [comment]
You may need to extract the whole zip to a folder such as c:\tedit

**Comment by CodyKurr** [comment]
Okay, that fixed the problem. Thank you for your help, and countinue your great work.
