### ISSUE TITLE
terraria system out of memory Help plz

### ISSUE THREAD

**Issue by SethTrull** [TEdit/Terraria-Map-Editor#1018]
---------------------------
Terraria: Error
---------------------------
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.

   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawIndexedPrimitives(PrimitiveType primitiveType, Int32 baseVertex, Int32 minVertexIndex, Int32 numVertices, Int32 startIndex, Int32 primitiveCount)

   at Microsoft.Xna.Framework.Graphics.SpriteBatch.PlatformRenderBatch(Texture2D texture, SpriteInfo[] sprites, Int32 offset, Int32 count)

   at Microsoft.Xna.Framework.Graphics.SpriteBatch.RenderBatch(Texture2D texture, SpriteInfo[] sprites, Int32 offset, Int32 count)

   at Microsoft.Xna.Framework.Graphics.SpriteBatch.Flush()

   at Microsoft.Xna.Framework.Graphics.SpriteBatch.End()

   at Terraria.Main.RenderBackground()

   at Terraria.Main.do_Draw(GameTime gameTime)

   at Terraria.Main.DoDraw(GameTime gameTime)

   at Terraria.Main.Draw(GameTime gameTime)

   at Microsoft.Xna.Framework.Game.DrawFrame()

   at Microsoft.Xna.Framework.Game.Tick()

   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)

   at Microsoft.Xna.Framework.GameHost.OnIdle()

   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()

   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)

   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)

   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)

   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)

   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)

   at System.Windows.Forms.Application.Run(Form mainForm)

   at Microsoft.Xna.Framework.WindowsGameHost.Run()

   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)

   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
---------------------------
OK   
---------------------------

that is what it said i have no clue on what to do plz help

**Comment by BinaryConstruct** [comment]
This is not for Terraria issues, only TEdit. Please try the official forums.

**Comment by BigmenPixel0** [comment]
Having the same error after editing the world with TEdit
