### ISSUE TITLE
Randon Error.

### ISSUE THREAD

**Issue by ThatsFluke** [TEdit/Terraria-Map-Editor#1056]
I am using Terraria 1.3.5 and opened a vanilla world in Tedit! Scrolled into a building and had an error;

01-16-2018 17:32:56: Starting TEdit 3.10.17116.2025 
01-16-2018 17:32:56: OS: Microsoft Windows NT 6.2.9200.0 
01-16-2018 17:32:56: Terraria v1.3.5.3 
01-16-2018 17:32:56: Terraria Data Path: D:\Steam Library\steamapps\common\Terraria\Content 
01-16-2018 17:32:57: Creating Undo cache: C:\Users\lukeb\AppData\Roaming\TEdit\undo_579245869 
01-16-2018 17:33:22: Failed to load texture: Images\Item_-14 
01-16-2018 17:33:22: The content file was not found. 
01-16-2018 17:33:22: Error - Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at TEditXna.View.WorldRenderXna.DrawSprites() in C:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:line 825
   at TEditXna.View.WorldRenderXna.Render(GraphicsDeviceEventArgs e) in C:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:line 381
   at TEditXna.View.WorldRenderXna.xnaViewport_RenderXna(Object sender, GraphicsDeviceEventArgs e) in C:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:line 302
   at TEdit.UI.Xaml.XnaContentHost.GraphicsDeviceControl.CompositionTarget_Rendering(Object sender, EventArgs e) in C:\projects\terraria-map-editor\TEditXna\UI\Xaml\XnaContentHost\GraphicsDeviceControl.cs:line 328
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at TEditXna.App.Main() 

WHAT IS ITEM 14?!?!?!?!?!?

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are #779 (Unhandled Exception), #901 (Crashes due to an "unhandled exeption"), #778 (Unhandled Exception), #755 (Error Loading Corrupt World), and #881 (Terraria world corrupted and need help).

**Comment by Beastingaming36** [comment]
ok.
