### ISSUE TITLE
log error

### ISSUE THREAD

**Issue by Mohammadwh** [TEdit/Terraria-Map-Editor#1065]
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at TEditXna.App.Main()

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/897 (black map. checked error logs and nothing came up.), https://github.com/TEdit/Terraria-Map-Editor/issues/1038 (Better Log Messages), https://github.com/TEdit/Terraria-Map-Editor/issues/1021 (Error Help!), https://github.com/TEdit/Terraria-Map-Editor/issues/314 (Microsoft.Xna.Framework.Graphics.DeviceLostException), and https://github.com/TEdit/Terraria-Map-Editor/issues/334 (Could not find a graphics device that supports the XNA Framework Reach profile).
