### ISSUE TITLE
Issue with opening world file.

### ISSUE THREAD

**Issue by Gastik1** [TEdit/Terraria-Map-Editor#1109]
I opened TEdit for the first time, and went to open, and selected my world.

I could reproduce the issue if need be. I have before.

I was using Terraria version 1.3.5.3

Log:
09-13-2018 18:03: Starting TEdit 3.5.18256.1801 
09-13-2018 18:03: OS: Microsoft Windows NT 6.2.9200.0 
09-13-2018 18:03: .Net >= 4.0 
09-13-2018 18:03: XNA 4.0 
09-13-2018 18:03: Terraria Data Path: c:\gog games\terraria\Content 
09-13-2018 18:03: Creating Undo cache: C:\Users\Dan 2 hehe xd\AppData\Roaming\TEdit\undo_63609627 
09-13-2018 18:11: Error - Object reference not set to an instance of an object.
   at TEditXna.ViewModel.WorldViewModel.MouseMoveTile(TileMouseState e) in c:\Users\Dan 2 hehe xd\Desktop\TEdit\Terraria-Map-Editor-d0446702525cb99657b5f9b1ae80aff8f4696fd0\TEditXna\ViewModel\WorldViewModel.cs:line 617
   at TEditXna.View.WorldRenderXna.xnaViewport_HwndMouseMove(Object sender, HwndMouseEventArgs e) in c:\Users\Dan 2 hehe xd\Desktop\TEdit\Terraria-Map-Editor-d0446702525cb99657b5f9b1ae80aff8f4696fd0\TEditXna\View\WorldRenderXna.xaml.cs:line 1586
   at TEdit.UI.Xaml.XnaContentHost.GraphicsDeviceControl.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in c:\Users\Dan 2 hehe xd\Desktop\TEdit\Terraria-Map-Editor-d0446702525cb99657b5f9b1ae80aff8f4696fd0\TEditXna\UI\Xaml\XnaContentHost\GraphicsDeviceControl.cs:line 596
   at System.Windows.Interop.HwndHost.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at TEditXna.App.Main() in c:\Users\Dan 2 hehe xd\Desktop\TEdit\Terraria-Map-Editor-d0446702525cb99657b5f9b1ae80aff8f4696fd0\TEditXna\obj\x86\Release\App.g.cs:line 0 

Extra info: TEdit said when I started it: "Could not check version."

**Comment by BinaryConstruct** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/TEdit/Terraria-Map-Editor/issues/654 (Tedit wont open a world), https://github.com/TEdit/Terraria-Map-Editor/issues/586 (Cannot open world after substantial edits to base), https://github.com/TEdit/Terraria-Map-Editor/issues/624 (Cant open worlds), https://github.com/TEdit/Terraria-Map-Editor/issues/333 (Initialization issue), and https://github.com/TEdit/Terraria-Map-Editor/issues/398 (Opening world error).

**Comment by BinaryConstruct** [comment]
Are you compiling or using one of the builds from the releases page?
