### ISSUE TITLE
Zooming in Crashes Program

### ISSUE THREAD

**Issue by BlackFinSwampert** [TEdit/Terraria-Map-Editor#1309]
**The Bug**
I was able to edit this particular world file just fine on version 4.0.0 beta-17. However, a few days later, attempting edits to this world causes the program to crash. Issue continues in version 4.0.0 beta-19. I  assume this is likely due to world/file changes that have happened somewhat recently.

**To Reproduce**
1. Load file
2. Zoom in using mouse scroll wheel
3. Once zoomed enough, the program will crash. It's semi-random, but seems to occur around the point where rendering switches from pixel colors to detailed tiles.

**Output Log**
06-14-2020 08:39:37: Starting TEdit 4.0.0.0 
06-14-2020 08:39:37: OS: Microsoft Windows NT 10.0.18362.0 
06-14-2020 08:39:37: OS Name: Microsoft Windows 10 Pro  
06-14-2020 08:39:37: .NET Framework Version: 4.8 or later 
06-14-2020 08:39:37: Terraria v1.4.0.5 
06-14-2020 08:39:37: Terraria Data Path: D:\Program Files (x86)\SteamLibrary\steamapps\common\Terraria\Content 
06-14-2020 08:39:38: Creating Undo cache: C:\Users\The Dragon Den\AppData\Roaming\TEdit\undo_497510444 
_(Editor's note; point where at zooming in)_
06-14-2020 08:42:16: Error - The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TEdit.View.WorldRenderXna.DrawTileEntities()
   at TEdit.View.WorldRenderXna.Render(GraphicsDeviceEventArgs e)
   at TEdit.View.WorldRenderXna.xnaViewport_RenderXna(Object sender, GraphicsDeviceEventArgs e)
   at TEdit.UI.Xaml.XnaContentHost.GraphicsDeviceControl.CompositionTarget_Rendering(Object sender, EventArgs e)
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at TEdit.App.Main() 
_(Editor's Note: "An unhandled exception has occurred. Please copy the log from [Directory]TEditLog.txt to the GitHub Issues list. The program will now exit.")_

**Desktop**
 - OS: Windows 10
 - Version: TEdit 4.0.0, beta-17 and beta-19
 - Terraria Version: 1.4.0.5, Steam edition

**Additional Info**
I have an older version of the world file in question backed up that I was successfully able to edit in the past. I can provide this version and the new version that causes the crash if it would be helpful in identifying the problem.

**Comment by BinaryConstruct** [comment]
Would you attach a zipped world file please?

**Comment by BinaryConstruct** [comment]
Work is in progress in this. The fix is a bit larger than I expected, may need another day. Same issue as #1308

**Comment by BinaryConstruct** [comment]
Please try beta 20 and reopen with a world file attached if you are still having issues.

https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.0.0-beta20
