### ISSUE TITLE
switching maps cause crash

### ISSUE THREAD

**Issue by lathemandrel** [TEdit/Terraria-Map-Editor#1324]
switching from a map initially created in terraria 1.3.5, to one initially created in 1.4 causes a crash. only seems to happen if the first map has a section "highlighted" with the selection tool. the [block tags] page is 404 so i hope this is an acceptable posting.

edit; seems now that it is the 1.4 map being zoomed in that causes the same crash.

Windows 7
Terraria 1.4.0.5
Tedit4 beta21

```

06-18-2020 17:48:29: Starting TEdit 4.0.0.0 
06-18-2020 17:48:29: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
06-18-2020 17:48:29: OS Name: Microsoft Windows 7 Ultimate Service Pack 1 
06-18-2020 17:48:29: .NET Framework Version: 4.8 or later 
06-18-2020 17:48:30: Terraria v1.4.0.5 
06-18-2020 17:48:30: Terraria Data Path: C:\Program Files (x86)\Steam\steamapps\common\Terraria\Content 
06-18-2020 17:48:31: Creating Undo cache: C:\Users\----\AppData\Roaming\TEdit\undo_230164613 
06-18-2020 17:51:41: Error - The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TEdit.View.WorldRenderXna.DrawTileEntities()
   at TEdit.View.WorldRenderXna.Render(GraphicsDeviceEventArgs e)
   at TEdit.View.WorldRenderXna.xnaViewport_RenderXna(Object sender, GraphicsDeviceEventArgs e)
   at TEdit.UI.Xaml.XnaContentHost.GraphicsDeviceControl.CompositionTarget_Rendering(Object sender, EventArgs e)
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at TEdit.App.Main() 


```

**Comment by BinaryConstruct** [comment]
It looks like it is missing a texture for a tile that it is trying to render. Can you attach the map?

**Comment by lathemandrel** [comment]
specifically, i have to turn off "Textures" for it to work. using beta23 i can zoom in somewhat more before the same error log is generated. i will email you the map itself, as i am not ready to post it publicly yet.

**Comment by lathemandrel** [comment]
map and its slightly updated versions, both cause the same error. i
havnt checked if any previous versions are also errored.

**Comment by lathemandrel** [comment]
i emailed that last response, including a zip file, expecting it to not be public, and not expecting it to post the text and not the zip. did you get the zip, and if not, what can i do to send it to you, and not post it in  a comment?

**Comment by BinaryConstruct** [comment]
You can DM me on Twitter or Gmail to my user username.
