### ISSUE TITLE
crash when flipping objects on the y coordinate

### ISSUE THREAD

**Issue by Ethan3F** [TEdit/Terraria-Map-Editor#1327]
```
06-19-2020 00:38:25: Starting TEdit 4.0.0.0 
06-19-2020 00:38:25: OS: Microsoft Windows NT 10.0.18363.0 
06-19-2020 00:38:25: OS Name: Microsoft Windows 10 Home  
06-19-2020 00:38:25: .NET Framework Version: 4.8 or later 
06-19-2020 00:38:26: Terraria v1.4.0.5 
06-19-2020 00:38:26: Terraria Data Path: C:\Program Files (x86)\Steam\steamapps\common\Terraria\Content 
06-19-2020 00:38:26: Creating Undo cache: C:\Users\flemi\AppData\Roaming\TEdit\undo_274985156 
06-19-2020 00:59:26: Error - Object reference not set to an instance of an object.
   at TEdit.Render.PixelMap.GetTileColor(Tile tile, Color background, Boolean showWall, Boolean showTile, Boolean showLiquid, Boolean showRedWire, Boolean showBlueWire, Boolean showGreenWire, Boolean showYellowWire)
   at TEdit.Editor.Clipboard.ClipboardBuffer.RenderBuffer()
   at TEdit.Editor.Clipboard.ClipboardManager.Flip(ClipboardBuffer buffer, Boolean flipX) 
06-19-2020 00:59:26: Error - Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at GalaSoft.MvvmLight.Helpers.WeakAction`1.Execute(T parameter)
   at GalaSoft.MvvmLight.Command.RelayCommand`1.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at TEdit.App.Main() 
```

**Comment by BinaryConstruct** [comment]
Can you attach the schematic and wold file as a zip?

**Comment by LadySaga** [comment]
I literally just opened up my Github account for the first time in many many years to report the same issue. :)
It was working in .21, no idea about .22 since I missed that update, but yeah, I also get unexpected crashes when flipping things.
For me it doesn't matter if it's an imported schematic, or just a select copy paste flip.
After seeing your question about the schematic I also tried different things, and it doesn't seem to matter if it contains wire or not, new 1.4 blocks or not, just air and dirt or not, and so on. For me it happens for everything I try to flip, on any map, including a completely empty New Map.

**Comment by BinaryConstruct** [comment]
It is at the top of my list, until I can get a fix out I suggest using beta 20 or 19, even though it is missing some rendering of you need to flip the clipboard.
