### ISSUE TITLE
Crash after copying a new 1.4 block

### ISSUE THREAD

**Issue by Anto3oo** [TEdit/Terraria-Map-Editor#1328]
So yeah , i was trying to copy something and paste it in another position in my terraria 1.4.0.5 world , but the area that i copied contained some 1.4 blocks (they didnt have any texture , expecifically , it was the Blue Starry Block , this crash happens everytime i copy something with a 1.4.0.4 + block , those with that pink color because they have no texture ,
Here is my log:

```
06-19-2020 08:58:22: Starting TEdit 4.0.0.0 
06-19-2020 08:58:22: OS: Microsoft Windows NT 10.0.18362.0 
06-19-2020 08:58:22: OS Name: Microsoft Windows 10 Home  
06-19-2020 08:58:22: .NET Framework Version: 4.8 or later 
06-19-2020 08:58:23: Unable to locate Terraria. No texture data will be available. 
06-19-2020 08:58:23: Creating Undo cache: C:\Users\USUARIO\AppData\Roaming\TEdit\undo_69716037 
06-19-2020 08:59:50: Error - Object reference not set to an instance of an object.
   at TEdit.Terraria.World.GetAnchor(Int32 x, Int32 y)
   at TEdit.Editor.Clipboard.ClipboardManager.GetSelectionBuffer()
   at TEdit.ViewModel.WorldViewModel.EditCopy() 
06-19-2020 08:59:50: Error - Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at GalaSoft.MvvmLight.Helpers.WeakAction.Execute()
   at GalaSoft.MvvmLight.Command.RelayCommand.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at TEdit.App.Main() 
```

**Comment by BinaryConstruct** [comment]
Could you attach the world file as a zip and point me to the relevant location? Thanks.

**Comment by Anto3oo** [comment]
[Galaxy - Copy.zip](https://github.com/TEdit/Terraria-Map-Editor/files/4805472/Galaxy.-.Copy.zip)
Here you go , i was trying to copy that sort of ship over those mahogany trees  in the west

**Comment by BinaryConstruct** [comment]
Hmm, are you using beta 22? I was able to copy paste it successfully:
![image](https://user-images.githubusercontent.com/456755/85156659-fe653f80-b21f-11ea-9312-399e8a49fe67.png)

**Comment by BinaryConstruct** [comment]
See if this helps 
https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.0.0-beta23

**Comment by Anto3oo** [comment]
Thanks a lot , looks like some data was missing
