### ISSUE TITLE
Unhandled Exception crash when opening a world

### ISSUE THREAD

**Issue by noodlius** [TEdit/Terraria-Map-Editor#1418]
I get an unhandled exception message when I try open my world. I've edited this world before but suddenly I can't open it up anymore. 

![2020-10-14 (3)_LI_Moment](https://user-images.githubusercontent.com/72865365/95982209-20627d80-0e20-11eb-95a0-9a1fdce3db93.jpg)

I'm running Windows 10, TEdit4 Beta 33, and Terraria 1.4.1

Log in comments

**Comment by noodlius** [comment]
```
10-14-2020 13:01:45: Starting TEdit 4.0.0.0 
10-14-2020 13:01:45: OS: Microsoft Windows NT 10.0.18362.0 
10-14-2020 13:01:45: OS Name: Microsoft Windows 10 Home  
10-14-2020 13:01:45: .NET Framework Version: 4.8 or later 
10-14-2020 13:01:46: Terraria v1.4.1.0 
10-14-2020 13:01:46: Terraria Data Path: C:\Program Files (x86)\Steam\steamapps\common\Terraria\Content 
10-14-2020 13:01:46: Command Line Open: C:\Users\Merete Goosen\Documents\My Games\Terraria\Worlds\Dreamland_of_Fish.wld 
10-14-2020 13:01:47: Creating Undo cache: C:\Users\Merete Goosen\AppData\Roaming\TEdit\undo_567231862 
10-14-2020 13:02:15: Error - Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at TEdit.View.WorldRenderXna.DrawNpcOverlay(NPC npc)
   at TEdit.View.WorldRenderXna.DrawNpcTexture(NPC npc)
   at TEdit.View.WorldRenderXna.DrawPoints()
   at TEdit.View.WorldRenderXna.Render(GraphicsDeviceEventArgs e)
   at TEdit.View.WorldRenderXna.xnaViewport_RenderXna(Object sender, GraphicsDeviceEventArgs e)
   at TEdit.UI.Xaml.XnaContentHost.GraphicsDeviceControl.CompositionTarget_Rendering(Object sender, EventArgs e)
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.AnimatedRenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at TEdit.App.Main() 
```

**Comment by xXmartin0311** [comment]
I think 1.4.1 broke it, you have to wait for it to be updated

**Comment by B00ie23** [comment]
This is due to the new Princess NPC added in 1.4.1, TEdit does not have her sprites and the world will not be accessible as long as she's present in the world.
Try to despawn her in-game somehow (lava, enemies, or even water) and then save & exit as soon as she despawns.

**Comment by BinaryConstruct** [comment]
See #1427
