### ISSUE TITLE
Unhandled Exception - Won't load my world

### ISSUE THREAD

**Issue by Aermay** [TEdit/Terraria-Map-Editor#1447]
```
11-02-2020` 08:26:55: Starting TEdit 4.0.0.0 
11-02-2020 08:26:55: OS: Microsoft Windows NT 10.0.19041.0 
11-02-2020 08:26:55: OS Name: Microsoft Windows 10 Home  
11-02-2020 08:26:55: .NET Framework Version: 4.8 or later 
11-02-2020 08:27:01: Terraria v1.4.1.1 
11-02-2020 08:27:01: Terraria Data Path: D:\Program Files\Steam\steamapps\common\Terraria\Content 
11-02-2020 08:27:02: Creating Undo cache: C:\Users\mcpan\AppData\Roaming\TEdit\undo_155105323 
11-02-2020 08:27:46: Error - Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at TEdit.View.WorldRenderXna.DrawNpcOverlay(NPC npc)
   at TEdit.View.WorldRenderXna.DrawNpcTexture(NPC npc)
   at TEdit.View.WorldRenderXna.DrawPoints()
   at TEdit.View.WorldRenderXna.Render(GraphicsDeviceEventArgs e)
   at TEdit.View.WorldRenderXna.xnaViewport_RenderXna(Object sender, GraphicsDeviceEventArgs e)
   at TEdit.UI.Xaml.XnaContentHost.GraphicsDeviceControl.CompositionTarget_Rendering(Object sender, EventArgs e)
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at `TEdit.App.Main()
```

**Describe the bug**
I have a Tedit shortcut is on my desktop. It opens fine, but when I try to open my saved world, it gives me the error and then immediately closes. This only happens with one specific world I'm trying to open.

**To Reproduce**
1. Go to Tedit
2. Click on File>Open>My world
3. See error

**Expected behavior**
I expect my world to open.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version [Tedit 4 beta 31]
 - Terraria Version [e.g. 1.4.1.1]

**Comment by BinaryConstruct** [comment]
Could you please attach a ZIP file of your world? Thanks!

**Comment by Aermay** [comment]
[Files.zip](https://github.com/TEdit/Terraria-Map-Editor/files/5476302/Files.zip)

**Comment by BinaryConstruct** [comment]
Hmm, it was able to load the files without any issues. Cool world BTW.  

Here are some things to try:

1. Delete the cache folder `%appdata%\tedit`
1. Delete the settings folder `%localappdata%\tedit`
1. Delete the folder you have unzipped TEdit into and download a fresh copy.
1. Unzip the new download into an empty folder, such as c:\games\tedit.

![image](https://user-images.githubusercontent.com/456755/98009009-b99b0900-1dba-11eb-9b23-9beee1022c6a.png)

**Comment by Aermay** [comment]
That worked! Thank you. 

This is actually my daughter's world that she likes to RP in, but I used Tedit to throw in some of my builds from my adventure map I'm making. I normally wouldn't care about opening it in Tedit, but I made a movie theater for her and thought it was pretty cool so I wanted to save the schematic of it rather than remake it.

Thanks for all the help!

**Comment by BinaryConstruct** [comment]
Happy to help! I'm glad that worked.
