### ISSUE TITLE
Application wont start

### ISSUE THREAD

**Issue by Lunasycthe** [TEdit/Terraria-Map-Editor#1470]
TEdit wont start, I get the green icon pop up, then it's terminated before it can even make an error log. I've tried the fixes and moved it around, though I'd rather keep Terraria on my D drive with all the other games for space. I'm on a new laptop so there's no previous versions or anything set up at all. It may be a dotnet problem? I think I updated it, but I'm really not an expert on all this... This is what it's throwing this in the event viewer up after I updated dotnet. It's probably just something I've missed...

First error:
Faulting application name: TEdit.exe, version: 4.2.3.0, time stamp: 0x8daec656
Faulting module name: KERNELBASE.dll, version: 10.0.19041.572, time stamp: 0x1183946c
Exception code: 0xe0434352
Fault offset: 0x0000000000023e49
Faulting process ID: 0x4364
Faulting application start time: 0x01d6e76d8664cef9
Faulting application path: D:\TEdit4.2.3\TEdit.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report ID: 74fc2280-825c-4ced-b721-1cac1b1f9fe6
Faulting package full name: 
Faulting package-relative application ID: 

Second error:
Application: TEdit.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.UnauthorizedAccessException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32)
   at TEdit.ErrorLogging.Initialize()
   at TEdit.App.OnStartup(System.Windows.StartupEventArgs)
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at TEdit.App.Main()

Screenshot of the event viewer:
![image](https://user-images.githubusercontent.com/37459736/104129013-96647b00-5362-11eb-86c4-76678d3b3068.png)

**Comment by BinaryConstruct** [comment]
Looks like TEdit does not have write access to its own folder or one of the cache folders. It might not have access to read the Terraria folder.

**Comment by Lunasycthe** [comment]
I've given it full control in folder permissions, I've tried running it as admin, and I've done a search on the c drive and deleted everything that had TEdit on it, including some things in appdata that werent there before. Still no change, the error is the same in the event viewer. Even changed the KERNELBASE.dll to make sure it had access, still nothing. This is frustrating, I was looking forward to making some new maps.

**Comment by Lunasycthe** [comment]
Well I tried all sorts of things, still no luck. Finally decided to try using 4.2.2, and that works fine, so if there's no major updates between the two versions I guess I'll use that...

**Comment by BinaryConstruct** [comment]
Interesting. That may actually help me track down the issue. I'll investigate and see if I can find something.

**Comment by BinaryConstruct** [comment]
Can you try this release?
https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.2.4

**Comment by Lunasycthe** [comment]
Yay, I just accidentally erased all my tedit back ups due to trying to get onedrive to stop backing them up since originally for a split second I get a error saying it didnt have access to onedrive... I swear trying to stop onedrive is like trying to erase mcfee... Good thing I manually backed up the files a couple of times... Anyway once I managed to stop it attempting to access onedrive it wouldnt access the my documents folder either. Looking at it I think the problem is it's not creating the log file, I checked the log folder it's referring to and it's always been empty. I'd try putting a notepad in there with the name, but the number on it keeps changing. Still got the same error in event viewer, though this could be the access problem. 

![image](https://user-images.githubusercontent.com/37459736/104768405-7f0ffe00-5765-11eb-8954-1db426a66392.png)

**Comment by BinaryConstruct** [comment]
This error message was very helpful. Please try this release https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.2.5 It should address the onedrive access denied issue.

**Comment by Lunasycthe** [comment]
Nice, looks like it's working now! Though I do still have onedrive turned off I was getting that previous error even with it off, so I presume this just bypasses the entire access problem whether it's on or off. I'm happy to help something I'm sunk so much time into , probably even more than the actual game... 

Now the mod is perfect to me except one little thing, the tree tops option is a bit odd. I've been screenshotting and documenting the backgrounds and tree tops since some backgrounds and the tree tops dont line up with the terraria wiki, so I've been making my own guide for them, I can post that up to help others with the correlating numbers if you want. Tree tops 31, 51, 71, 72, and 73 all crash the game when attempting to view them. 
![image](https://user-images.githubusercontent.com/37459736/104794931-e0a28d80-57a2-11eb-8608-5aa5ceff1302.png)
Also tree tops 6 and 8 I presume dont fit on the wrong tree trunk? Or the animation is placed/cropped oddly. 
![image](https://user-images.githubusercontent.com/37459736/104795239-98846a80-57a4-11eb-8f14-44690e52675d.png)
![image](https://user-images.githubusercontent.com/37459736/104795003-37a86280-57a3-11eb-8a70-cf6765d6bebd.png)

But this is only a small nitpick, it works as I want it to otherwise so I'm personally not too fussed if you leave it, or just put a warning somewhere not to use the last few tree tops.
