### ISSUE TITLE
Tedit only allows me to place around 1000 blocks before not allowing me to place any more.

### ISSUE THREAD

**Issue by Ferrarisrex** [TEdit/Terraria-Map-Editor#1698]
Every time I open TEdit, and I load a world. I can only edit around 1000 blocks before the paintbrush tool no longer functions, and neither does the hammer

Open the application, load a world, and edit it. only allows 1000 or so edits before becoming uneditable.

I would expect it to keep allowing me to place blocks

![image](https://user-images.githubusercontent.com/91031616/194649912-e8b57207-1e57-43e6-b0f3-f0706d99add1.png)
no more blocks after this many

**Desktop (please complete the following information):**
 Windows 11
 TEdit v4.11.2
 1.4.4.5

**Comment by Ferrarisrex** [comment]
Also, if I save it, then open it again, it did not save

**Comment by ajpircio** [comment]
This happens for me too, I also get this in the logs every time I click with the brush (or the pencil)

10-07-2022 16:48:27: Error - The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TEdit.Editor.Undo.UndoBuffer.SaveTileData()
   at TEdit.Editor.Undo.UndoBuffer.Close()
   at TEdit.Editor.Undo.UndoManager.SaveUndo(Boolean updateMax)
   at TEdit.Editor.Tools.PencilTool.MouseUp(TileMouseState e)
   at TEdit.ViewModel.WorldViewModel.MouseUpTile(TileMouseState e)
   at TEdit.View.WorldRenderXna.xnaViewport_HwndLButtonUp(Object sender, HwndMouseEventArgs e)
   at TEdit.UI.Xaml.XnaContentHost.GraphicsDeviceControl.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

**Comment by Ferrarisrex** [comment]
also, after launching the application, the X button for terraria is greyed out and non functional.
![image](https://user-images.githubusercontent.com/91031616/194650525-9d7e436e-bb27-43ed-8e8b-2f928e495ad3.png)

**Comment by mappy11** [comment]
> The given key was not present in the dictionary.

this problem also found in #1695.

**Comment by RussDev7** [comment]
Resolved in our latest builds. Thanks.
