### ISSUE TITLE
Unsaved Terraria World File

### ISSUE THREAD

**Issue by Erugahn** [TEdit/Terraria-Map-Editor#246]
My computer shut down while I was playing Terraria, resulting in an unsaved world. When I went on to play, I could not open it up, even though it took up a space in the world list and in the Terraria world folders it was still there. I tried using TEdit to fix the problem, but it didn't work, and in the log.txt was this message:

```
01-31-2012 21:33 v3.1.12019.2351 Error - Index was outside the bounds of the array.
   at TEditXna.ViewModel.WorldViewModel.MouseMoveTile(TileMouseState e) in D:\Dev\_PROJECTS\Terraria\Terraria-Map-Editor\TEditXna\ViewModel\WorldViewModel.cs:line 354
   at TEditXna.View.WorldRenderXna.xnaViewport_HwndMouseMove(Object sender, HwndMouseEventArgs e) in D:\Dev\_PROJECTS\Terraria\Terraria-Map-Editor\TEditXna\View\WorldRenderXna.xaml.cs:line 710
   at BCCL.UI.Xaml.XnaContentHost.GraphicsDeviceControl.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in D:\Dev\_PROJECTS\BCCL\BCCL.Xna\UI\Xaml\XnaContentHost\GraphicsDeviceControl.cs:line 596
   at System.Windows.Interop.HwndHost.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at TEditXna.App.Main() in D:\Dev\_PROJECTS\Terraria\Terraria-Map-Editor\TEditXna\obj\x86\Release\App.g.cs:line 0 
01-31-2012 21:33 v3.1.12019.2351 Error - '-291' is not a valid value for property 'ViewportSize'.
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at TEditXna.View.WorldRenderXna.Zoom(Int32 direction) in D:\Dev\_PROJECTS\Terraria\Terraria-Map-Editor\TEditXna\View\WorldRenderXna.xaml.cs:line 756
   at TEditXna.View.WorldRenderXna._wvm_PropertyChanged(Object sender, PropertyChangedEventArgs e) in D:\Dev\_PROJECTS\Terraria\Terraria-Map-Editor\TEditXna\View\WorldRenderXna.xaml.cs:line 103
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at BCCL.MvvmLight.ObservableObject.RaisePropertyChanged(String propertyName) in D:\Dev\_PROJECTS\BCCL\BCCL\MvvmLight\ObservableObject.cs:line 109
   at BCCL.MvvmLight.ObservableObject.Set[T](String propertyName, T& field, T newValue) in D:\Dev\_PROJECTS\BCCL\BCCL\MvvmLight\ObservableObject.cs:line 192
   at TEditXna.ViewModel.WorldViewModel.<LoadWorld>b__26(Task`1 t) in D:\Dev\_PROJECTS\Terraria\Terraria-Map-Editor\TEditXna\ViewModel\WorldViewModel.cs:line 472
   at System.Threading.Tasks.Task`1.<>c__DisplayClass1a`1.<ContinueWith>b__19()
   at System.Threading.Tasks.Task`1.InvokeFuture(Object futureAsObj)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute() 
```

**Comment by Adeonek** [comment]
is anyone still here after 3 years? :D got the same damn problem :/
https://www.dropbox.com/s/lvnoum79z3cacn4/Worlds.rar?dl=0

**Comment by SBlogic** [comment]
@Adeonek - I examined the data in the archive.  Sprite.wld appears to have only header data with nothing else, and Sprite.wld.bak is a 10MB zero-filled file.  There's absolutely no data in those files that TEdit would be able to load and reconstruct, sorry.

**Comment by Adeonek** [comment]
ou...damn it :( but still thanks for help
