### ISSUE TITLE
My Terraria world won't load.

### ISSUE THREAD

**Issue by Malokiua** [TEdit/Terraria-Map-Editor#248]
I was using TEdit for a terraria world, as usual, but one time it wouldn't load. I tried going on the actual terraria game and it wanted to load the backup. I did the same but it said that the backup had failed and now there is no backup. I cannot load this terraria world in anyway possible, although a lot of ingame time has been put into it. If somebody could help me revive it, I would be eternally grateful. The log.txt says:

```
02-02-2012 15:07 v3.1.12019.2351 Error - Index was outside the bounds of the array.
at TEditXna.ViewModel.WorldViewModel.MouseMoveTile(TileMouseState e) in D:\Dev_PROJECTS\Terraria\Terraria-Map-Editor\TEditXna\ViewModel\WorldViewModel.cs:line 354
at TEditXna.View.WorldRenderXna.xnaViewport_HwndMouseMove(Object sender, HwndMouseEventArgs e) in D:\Dev_PROJECTS\Terraria\Terraria-Map-Editor\TEditXna\View\WorldRenderXna.xaml.cs:line 710
at BCCL.UI.Xaml.XnaContentHost.GraphicsDeviceControl.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in D:\Dev_PROJECTS\BCCL\BCCL.Xna\UI\Xaml\XnaContentHost\GraphicsDeviceControl.cs:line 596
at System.Windows.Interop.HwndHost.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
at System.Windows.Application.RunDispatcher(Object ignore)
at System.Windows.Application.RunInternal(Window window)
at System.Windows.Application.Run(Window window)
at TEditXna.App.Main() in D:\Dev_PROJECTS\Terraria\Terraria-Map-Editor\TEditXna\obj\x86\Release\App.g.cs:line 0 
02-02-2012 15:10 v3.1.12019.2351 Error - Unable to read beyond the end of the stream.
at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
at System.IO.BinaryReader.ReadInt16()
at TEditXNA.Terraria.World.LoadWorld(String filename) in D:\Dev_PROJECTS\Terraria\Terraria-Map-Editor\TEditXna\Terraria\World.cs:line 731
at TEditXna.ViewModel.WorldViewModel.<>cDisplayClass28.b27() in D:\Dev_PROJECTS\Terraria\Terraria-Map-Editor\TEditXna\ViewModel\WorldViewModel.cs:line 471
at System.Threading.Tasks.Task1.InvokeFuture(Object futureAsObj)
at System.Threading.Tasks.Task.InnerInvoke()
at System.Threading.Tasks.Task.Execute() 
02-03-2012 14:57 v3.1.12019.2351 Error - Unable to read beyond the end of the stream.
at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
at System.IO.BinaryReader.ReadInt16()
at TEditXNA.Terraria.World.LoadWorld(String filename) in D:\Dev\_PROJECTS\Terraria\Terraria-Map-Editor\TEditXna\Terraria\World.cs:line 731
at TEditXna.ViewModel.WorldViewModel.<>c__DisplayClass28.<LoadWorld>b__27() in D:\Dev\_PROJECTS\Terraria\Terraria-Map-Editor\TEditXna\ViewModel\WorldViewModel.cs:line 471
at System.Threading.Tasks.Task1.InvokeFuture(Object futureAsObj)
at System.Threading.Tasks.Task.InnerInvoke()
at System.Threading.Tasks.Task.Execute()
```

I don't really have a clue what any of this means, and am hoping that someone would help me out. Thank you for your time.

**Comment by alanatjesters** [comment]
im looking for some help with my tedit for terraria..
it wont load any of my worlds :(

08-21-2017 04:33: Starting TEdit 3.3.13234.7
08-21-2017 04:33: OS: Microsoft Windows NT 6.0.6002 Service Pack 2
08-21-2017 04:33: .Net >= 4.0
08-21-2017 04:33: XNA 4.0
08-21-2017 04:33: Terraria Data Path: c:/program files/steam\steamapps\common\terraria\Content
08-21-2017 04:33: Error - This method does not accept null for this parameter.
Parameter name: data
at Microsoft.Xna.Framework.Graphics.Texture2D.CopyData[T](Int32 level, Nullable1 rect, T[] data, Int32 startIndex, Int32 elementCount, UInt32 options, Boolean isSetting) at Microsoft.Xna.Framework.Graphics.Texture2D.GetData[T](Int32 level, Nullable1 rect, T[] data, Int32 startIndex, Int32 elementCount)
at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e)
08-21-2017 04:33: Error - This method does not accept null for this parameter.
Parameter name: data
at Microsoft.Xna.Framework.Graphics.Texture2D.CopyData[T](Int32 level, Nullable1 rect, T[] data, Int32 startIndex, Int32 elementCount, UInt32 options, Boolean isSetting) at Microsoft.Xna.Framework.Graphics.Texture2D.GetData[T](Int32 level, Nullable1 rect, T[] data, Int32 startIndex, Int32 elementCount)
at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e)
08-21-2017 04:33: Error - This method does not accept null for this parameter.
Parameter name: data
at Microsoft.Xna.Framework.Graphics.Texture2D.CopyData[T](Int32 level, Nullable1 rect, T[] data, Int32 startIndex, Int32 elementCount, UInt32 options, Boolean isSetting) at Microsoft.Xna.Framework.Graphics.Texture2D.GetData[T](Int32 level, Nullable1 rect, T[] data, Int32 startIndex, Int32 elementCount)
at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e)
