### ISSUE TITLE
Unhandled exception when loading world

### ISSUE THREAD

**Issue by CartoonPiranha** [TEdit/Terraria-Map-Editor#559]
I am on version 3.5.14228.27 of TEdit and 1.4.2.1 of Terraria. After working on a map in TEdit, I attempted to load it in Terraria, which was only able to load the backup from around an hour beforehand. I have a manual backup which is more recent, but opening either the original file or the manual backup in TEdit results in this message near the end of the "UndoTiles" stage:

There was an error reading the world file, do you wish to force it anyway?
 WARNING: This may have unexpected results including corrupt world files and program crashes.

The error is:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at TEditXNA.Terraria.World.LoadTileData(BinaryReader r,Int32 maxX,Int32 maxY)
   at TEditXNA.Terraria.World.LoadV2(BinaryReader b, String filename, World w)
   TEditXNA.Terraria.World.LoadWorld(String filename)
```
Forcing it to load results in TEdit crashing with an unhandled exception and the following log:
```
09-05-2014 02:20: Starting TEdit 3.5.14228.27 
09-05-2014 02:20: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
09-05-2014 02:20: .Net = 4.0 
09-05-2014 02:20: XNA 4.0 
09-05-2014 02:20: Terraria Data Path: C:\Program Files (x86)\Steam\steamapps\common\Terraria\Content 
09-05-2014 02:20: Creating Undo cache: C:\Users\[hidden]\AppData\Roaming\TEdit\undo_599869467 
09-05-2014 02:43: Error - Object reference not set to an instance of an object.
   at TEditXna.View.WorldRenderXna.DrawSprites()
   at TEditXna.View.WorldRenderXna.Render(GraphicsDeviceEventArgs e)
   at TEditXna.View.WorldRenderXna.xnaViewport_RenderXna(Object sender, GraphicsDeviceEventArgs e)
   at TEdit.UI.Xaml.XnaContentHost.GraphicsDeviceControl.CompositionTarget_Rendering(Object sender, EventArgs e)
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object 
args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at TEditXna.App.Main() 
```

I've seen it mentioned in another issue that the IndexOutOfRange error can be caused by an object that TEdit does not recognise, sometimes from using a new version of Terraria, but the only changes made between the working version and the more recent ones were made in TEdit itself, and those versions have never been opened in Terraria.

**Comment by michelletan** [comment]
I am using the same versions of TEdit and Terraria as CartoonPiranha, and I got the exact same error in the log. My last action was placing honey inside a space surrounded by pearlstone bricks when it suddenly crashed. I wasn't doing anything else before my last save. The world file can't be opened in Terraria or TEdit now. Is there any way to recover the world file?
