### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by mitchellmebane** [TEdit/Terraria-Map-Editor#582]
I had TEdit open in the background while I was browsing some tutorials, and when I came back to it, it had crashed and told me to submit the log.  Might have been related to plugging my laptop in - I have an nVidia chip with Optimus crap, but I turned that off in the BIOS, so it should have been nVidia the whole time...

```
12-30-2014 13:29: Starting TEdit 3.5.14228.27 
12-30-2014 13:29: OS: Microsoft Windows NT 6.2.9200.0 
12-30-2014 13:29: .Net >= 4.0 
12-30-2014 13:29: XNA 4.0 
12-30-2014 13:29: Terraria Data Path: C:\Program Files (x86)\Steam\steamapps\common\Terraria\Content 
12-30-2014 13:29: Creating Undo cache: C:\Users\mmebane.MEBANEHOME\AppData\Roaming\TEdit\undo_994645546 
12-30-2014 21:38: Error - Exception of type 'Microsoft.Xna.Framework.Graphics.DeviceLostException' was thrown.
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Present(tagRECT* pSource, tagRECT* pDest, HWND__* hOverride)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Present(Nullable`1 sourceRectangle, Nullable`1 destinationRectangle, IntPtr overrideWindowHandle)
   at TEdit.UI.Xaml.XnaContentHost.GraphicsDeviceControl.CompositionTarget_Rendering(Object sender, EventArgs e) in c:\Atlassian\ApplicationData\Bamboo\xml-data\build-dir\TED-CI-JOB1\TEditXna\UI\Xaml\XnaContentHost\GraphicsDeviceControl.cs:line 340
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.AnimatedRenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at TEditXna.App.Main() in c:\Atlassian\ApplicationData\Bamboo\xml-data\build-dir\TED-CI-JOB1\TEditXna\obj\x86\Release\App.g.cs:line 0 
```

**Comment by BinaryConstruct** [comment]
This can happen when alt-tabbing or when running the game simultaneously. It is an issue with running XNA in a desktop client unlikely to be able to be fixed. Sorry for the inconvenience.
