### ISSUE TITLE
Cannot open world after substantial edits to base

### ISSUE THREAD

**Issue by flatbear** [TEdit/Terraria-Map-Editor#586]
I will offer as much information as I can about this world I was building.

It began as one generated by Terraria.  As I played, I felt dissatisfied with parts of the layout, so began to change it with TEdit.  I refilled the rooms I had dug out beneath a randomly generated giant tree near spawn; currently, the NPCs show as being in the ground.  Never been a problem before.

I made teleporter paths from my base to each ocean.  (I had saved and reloaded this world in TEdit many times since laying all the wire, so I don't think this could be the problem, but maybe.  It is a LOT of wire.)

Then I began to build a large tree out of living wood.  What's there is just the shape of the trunk and branches, filled in, without foliage or details yet.  That is where I left it last night.  I saved several times whilst working, and once more before shutting it down for the night.  A while ago, I tried to open the world again, and TEdit errored when trying to load it.

I have NOT played this world in Terraria since before I began all the changes, figuring I would sculpt a complete village before loading it again.  Now that it refuses to open with TEdit, I am afraid that opening it with Terraria will be dangerous. 

This is the error from the log: 

03-02-2015 12:53: Starting TEdit 3.5.14228.27 
03-02-2015 12:53: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
03-02-2015 12:53: .Net >= 4.0 
03-02-2015 12:53: XNA 4.0 
03-02-2015 12:53: Terraria Data Path: E:\Steam\steamapps\common\Terraria\Content 
03-02-2015 12:53: Creating Undo cache: C:\Users\dodgy mermaid\AppData\Roaming\TEdit\undo_25843161 
03-02-2015 12:53: Error - Object reference not set to an instance of an object.
   at TEditXna.ViewModel.WorldViewModel.MouseMoveTile(TileMouseState e)
   at TEditXna.View.WorldRenderXna.xnaViewport_HwndMouseMove(Object sender, HwndMouseEventArgs e)
   at TEdit.UI.Xaml.XnaContentHost.GraphicsDeviceControl.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndHost.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at TEditXna.App.Main() 

Here are links to the world and backup files:

http://www.filedropper.com/erynlasgalen
http://www.filedropper.com/erynlasgalenwld

Thanks for your time and for all you do.

**Comment by Walkman100** [comment]
> That is where I left it last night. I saved several times whilst working, and once more before shutting it down for the night. A while ago, I tried to open the world again, and TEdit errored when trying to load it.

"A while ago", as in before you saved the world?

I would check that the version of Terraria that you have been using and the supported Terraria version of TEdit are the same.

**Comment by flatbear** [comment]
"A while ago" as in about twenty-five minutes before I made the post above.

My version of Terraria is current and I updated TEdit before I began to play again.  I was using it fine until the point described in my post.
