### ISSUE TITLE
Failing to Open a Corrupted World File

### ISSUE THREAD

**Issue by Sasook** [TEdit/Terraria-Map-Editor#589]
Hello all!

I recently downloaded TEdit, and I've attempted to run a corrupted world in hopes of copying and pasting into another world.  However, when I open the file, I am unable to view the world, and also, when I view a clean file, I can't open it up either and it comes up with a warning.  Any ideas as to what to do next?

Thanks!
Sasook

**Comment by Sasook** [comment]
Here is a log of what the program told me to copy:

04-26-2015 09:26: Starting TEdit 3.5.15047.30 
04-26-2015 09:26: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
04-26-2015 09:27: .Net >= 4.0 
04-26-2015 09:27: XNA 4.0 
04-26-2015 09:27: Unable to locate Terraria. No texture data will be available. 
04-26-2015 09:27: Creating Undo cache: C:\Users\Julian\AppData\Roaming\TEdit\undo_619929749 
04-26-2015 09:28: Error - Index was outside the bounds of the array.
   at TEditXna.ViewModel.WorldViewModel.MouseUpTile(TileMouseState e)
   at TEditXna.View.WorldRenderXna.xnaViewport_HwndLButtonUp(Object sender, HwndMouseEventArgs e)
   at TEdit.UI.Xaml.XnaContentHost.GraphicsDeviceControl.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndHost.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at TEditXna.App.Main()
