### ISSUE TITLE
Unhandled Exception Error

### ISSUE THREAD

**Issue by Mystil** [TEdit/Terraria-Map-Editor#599]
Was editing a newly created world for Drow Rules--hid terrain blocks and wall, just started selected paintbrush perimeters (heigh 2, width 200) and started to move the screen with middle-mouse button--when TEdit threw this error and crashed. Was downloading/installing new graphics drivers at the time--I know some programs don't play nice with TEdit, so that info might be useful.

06-27-2015 22:41: Starting TEdit 3.5.14228.27 
06-27-2015 22:41: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
06-27-2015 22:41: .Net >= 4.0 
06-27-2015 22:41: XNA 4.0 
06-27-2015 22:41: Terraria Data Path: d:\steam\steamapps\common\terraria\Content 
06-27-2015 22:41: Creating Undo cache: C:\Users\Mystil.Paramount\AppData\Roaming\TEdit\undo_390172516 
06-27-2015 22:44: Error - An unexpected error has occurred.
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.set_Viewport(Viewport value)
   at TEdit.UI.Xaml.XnaContentHost.GraphicsDeviceControl.CompositionTarget_Rendering(Object sender, EventArgs e)
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at TEditXna.App.Main()

**Comment by Walkman100** [comment]
> started to move the screen with middle-mouse button--when TEdit threw this error and crashed. Was downloading/installing new graphics drivers at the time

Middle mouse button? You should try that again, since I don't remember ever pressing middle mouse while using TEdit... could be the problem.

Also - TEdit is known to need good enough graphics for Terraria to be able to run, so I'm guessing if it's graphics dependent it probably did crash because of the graphics driver change.

Looking at the log:
> Error - An unexpected error has occurred.
at Microsoft.Xna.Framework.Graphics.GraphicsDevice.set_Viewport(Viewport value)

Well there you go. TEdit couldn't tell the graphics card to render the editor.
