### ISSUE TITLE
Error with new 1.3 terraria update

### ISSUE THREAD

**Issue by terrara** [TEdit/Terraria-Map-Editor#603]
I get this when trying to load a world with the newest TEedit.

0: Starting TEdit 3.5.15047.30 
06-30-2015 12:30: OS: Microsoft Windows NT 6.2.9200.0 
06-30-2015 12:30: .Net >= 4.0 
06-30-2015 12:30: XNA 4.0 
06-30-2015 12:30: Terraria Data Path: D:\SteamLibrary\steamapps\common\Terraria\Content 
06-30-2015 12:30: Creating Undo cache: C:\Users\David\AppData\Roaming\TEdit\undo_798806010 
06-30-2015 12:30: Error - This method does not accept null for this parameter.
Parameter name: data
   at Microsoft.Xna.Framework.Graphics.Texture2D.CopyData[T](Int32 level, Nullable`1 rect, T[] data, Int32 startIndex, Int32 elementCount, UInt32 options, Boolean isSetting)
   at Microsoft.Xna.Framework.Graphics.Texture2D.GetData[T](Int32 level, Nullable`1 rect, T[] data, Int32 startIndex, Int32 elementCount)
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 
06-30-2015 12:30: Error - Arithmetic operation resulted in an overflow.
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 

fix?
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 

Does anyone know how to fix?

**Comment by jbsaige** [comment]
I am getting quite a different error message when trying to load a new 1.3 world file.

```
There was an error reading the world file, do you wish to force it to load anyway?

WARNING: This may have unexpected results including corrupt world files and program crashes.

The error is :
System.IO.FileFormatException: Unexpected Position: Invalid File Format Section
   at TEditXNA.Terraria.World.LoadV2(BinaryReader b, String filename, World w) in \TEditXna\Terraria\World.FileV2.cs:line 486
   at TEditXNA.Terraria.World.LoadWorld(String filename) in \TEditXna\Terraria\World.cs:line 110
```

**Comment by SBlogic** [comment]
It's not updated for 1.3 yet and isn't going to support a new format world.  Work is in progress.

**Comment by TheHoodedTeddy13** [comment]
Please Keep us Posted so we know when it comes out!
