### ISSUE TITLE
Tedit not loading maps

### ISSUE THREAD

**Issue by timizorzom** [TEdit/Terraria-Map-Editor#613]
the error message output this into  a text file and told me to put it here.
so here it is:

07-15-2015 17:37: Starting TEdit 3.5.14228.27 
07-15-2015 17:37: OS: Microsoft Windows NT 5.1.2600 Service Pack 3 
07-15-2015 17:37: .Net >= 4.0 
07-15-2015 17:37: XNA 4.0 
07-15-2015 17:37: Terraria Data Path: C:\Program Files\Steam\steamapps\common\Terraria\Content 
07-15-2015 17:38: Creating Undo cache: C:\Documents and Settings\HP_Owner\Application Data\TEdit\undo_133649456 
07-15-2015 17:38: Error - This method does not accept null for this parameter.
Parameter name: data
   at Microsoft.Xna.Framework.Graphics.Texture2D.CopyData[T](Int32 level, Nullable`1 rect, T[] data, Int32 startIndex, Int32 elementCount, UInt32 options, Boolean isSetting)
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) in c:\Atlassian\ApplicationData\Bamboo\xml-data\build-dir\TED-CI-JOB1\TEditXna\View\WorldRenderXna.xaml.cs:line 233 
07-15-2015 17:38: Error - Arithmetic operation resulted in an overflow.
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) in c:\Atlassian\ApplicationData\Bamboo\xml-data\build-dir\TED-CI-JOB1\TEditXna\View\WorldRenderXna.xaml.cs:line 231 
07-15-2015 17:39: Error - Value does not fall within the expected range.
 
07-15-2015 17:39: Error - Value does not fall within the expected range.
   at System.Windows.Media.Imaging.WriteableBitmap..ctor(Int32 pixelWidth, Int32 pixelHeight, Double dpiX, Double dpiY, PixelFormat pixelFormat, BitmapPalette palette)
   at TEditXna.Render.RenderMiniMap.Render(World w) in c:\Atlassian\ApplicationData\Bamboo\xml-data\build-dir\TED-CI-JOB1\TEditXna\Render\RenderMiniMap.cs:line 14
   at TEditXna.ViewModel.WorldViewModel.<LoadWorld>b__1f(Task`1 t) in c:\Atlassian\ApplicationData\Bamboo\xml-data\build-dir\TED-CI-JOB1\TEditXna\ViewModel\WorldViewModel.cs:line 763
   at System.Threading.Tasks.Task`1.<>c__DisplayClass17.<ContinueWith>b__16(Object obj)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by speeder** [comment]
TEdit is nto done for 1.3 yet. (I mean, the code is done, but I am not an official Dev, I am waiting to the official dev to show up and make an official build)

**Comment by Netfirec4t** [comment]
@speeder Does that mean don't use TEdit with a 1.3 map yet?
