### ISSUE TITLE
[Someone Please Help Me]XNA Error

### ISSUE THREAD

**Issue by ArchineerLock** [TEdit/Terraria-Map-Editor#619]
When ever I attempt to load a world it gives me this error message: 

07-22-2015 07:19: Starting TEdit 3.5.14228.27 
07-22-2015 07:19: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
07-22-2015 07:19: .Net >= 4.0 
07-22-2015 07:19: XNA 4.0 
07-22-2015 07:19: Terraria Data Path: C:\Program Files (x86)\Steam\steamapps\common\Terraria\Content 
07-22-2015 07:19: Creating Undo cache: C:\Users\Ed.ford-PC\AppData\Roaming\TEdit\undo_936242089 
07-22-2015 07:19: Error - This method does not accept null for this parameter.
Parameter name: data
   at Microsoft.Xna.Framework.Graphics.Texture2D.CopyData[T](Int32 level, Nullable`1 rect, T[] data, Int32 startIndex, Int32 elementCount, UInt32 options, Boolean isSetting)
   at Microsoft.Xna.Framework.Graphics.Texture2D.GetData[T](Int32 level, Nullable`1 rect, T[] data, Int32 startIndex, Int32 elementCount)
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 
07-22-2015 07:19: Error - Arithmetic operation resulted in an overflow.
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 

I have the latest version of microsoft XNA Framework and the other requirements.

**Comment by ArchineerLock** [comment]
Can someone please help me?

**Comment by TheHoodedTeddy13** [comment]
Is it a 1.3 world?  Because those aren't supported yet.

**Comment by Walkman100** [comment]
@TheHoodedTeddy13 all the `Error - This method does not accept null for this parameter.` errors are from 1.3 worlds.

**Comment by ArchineerLock** [comment]
Ok thank you
