### ISSUE TITLE
Pasting of existing chests causes TEdit to crash.

### ISSUE THREAD

**Issue by THEJaxster** [TEdit/Terraria-Map-Editor#627]
Hello,  Using the latest from SBLogic's fork... every time I paste a chest(s) over existing chest(s), TEdit will crash.  This seems to be because of the chests being the same.  Is this know to be an error?  If I copy the chest(s), then delete the selection area, then paste, there is no crash.  This has been my solution, just wanting to bring this up in case there is a solution.  Thanks for all your hard work on making this wonderful program work with the latest version of Terraria!

**Comment by SBlogic** [comment]
Please provide the complete contents of your TEditLog.txt after the crash.  Also see if you can replicate it in the current stable version, 3.5.15047.30, with a 1.2.4.1 compatible map.  I'm not familiar with most things chest-related, so I can't personally guarantee an explanation or fix.  It's possible this is an unresolved issue with previous versions, not specific to my fork (which is not intended to serve as a replacement for the master source).  More information is needed.

**Comment by CyberZHG** [comment]
I've seen this kind of crush before:

![image](https://cloud.githubusercontent.com/assets/853842/9020104/0175bd10-382e-11e5-8763-4432c8daa68e.png)


```
Error - Object reference not set to an instance of an object.
   at TEditXna.Editor.Clipboard.ClipboardManager.PasteBufferIntoWorld(Vector2Int32 anchor) in f:\Terraria-Map-Editor\TEditXna\Editor\Clipboard\ClipboardManager.cs:line 223
   at TEditXna.Editor.Tools.PasteTool.PasteClipboard(Vector2Int32 anchor) in f:\Terraria-Map-Editor\TEditXna\Editor\Tools\PasteTool.cs:line 49
   at TEditXna.Editor.Tools.PasteTool.MouseDown(TileMouseState e) in f:\Terraria-Map-Editor\TEditXna\Editor\Tools\PasteTool.cs:line 28
   at TEditXna.ViewModel.WorldViewModel.MouseDownTile(TileMouseState e) in f:\Terraria-Map-Editor\TEditXna\ViewModel\WorldViewModel.cs:line 643
   at TEditXna.View.WorldRenderXna.xnaViewport_HwndLButtonDown(Object sender, HwndMouseEventArgs e) in f:\Terraria-Map-Editor\TEditXna\View\WorldRenderXna.xaml.cs:line 1592
   at TEdit.UI.Xaml.XnaContentHost.GraphicsDeviceControl.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in f:\Terraria-Map-Editor\TEditXna\UI\Xaml\XnaContentHost\GraphicsDeviceControl.cs:line 482
   at System.Windows.Interop.HwndHost.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at TEditXna.App.Main() in f:\Terraria-Map-Editor\TEditXna\obj\x86\Release\App.g.cs:line 0 
```

`ClipboardManager.cs`:
![image](https://cloud.githubusercontent.com/assets/853842/9020112/4bb9892e-382e-11e5-9e3a-7457c09edc5c.png)

![image](https://cloud.githubusercontent.com/assets/853842/9020122/65099004-382e-11e5-98b9-94135a4fed62.png)

**Comment by THEJaxster** [comment]
Thanks for the quick support SBlogic and CyberZHG!
