### ISSUE TITLE
TEdit crashes after loading world

### ISSUE THREAD

**Issue by plasma159** [TEdit/Terraria-Map-Editor#638]
This is the error log that I have

08-10-2015 20:17: Starting TEdit 3.5.14228.27 
08-10-2015 20:17: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
08-10-2015 20:17: .Net >= 4.0 
08-10-2015 20:17: XNA 4.0 
08-10-2015 20:17: Terraria Data Path: E:\SteamLibrary\steamapps\common\Terraria\Content 
08-10-2015 20:17: Creating Undo cache: C:\Users\Sean\AppData\Roaming\TEdit\undo_28544156 
08-10-2015 20:17: Error - This method does not accept null for this parameter.
Parameter name: data
   at Microsoft.Xna.Framework.Graphics.Texture2D.CopyData[T](Int32 level, Nullable`1 rect, T[] data, Int32 startIndex, Int32 elementCount, UInt32 options, Boolean isSetting)
   at Microsoft.Xna.Framework.Graphics.Texture2D.GetData[T](Int32 level, Nullable`1 rect, T[] data, Int32 startIndex, Int32 elementCount)
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 
08-10-2015 20:17: Error - Arithmetic operation resulted in an overflow.
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 
08-10-2015 20:18: Error - '-48' is not a valid value for property 'ViewportSize'.
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at TEditXna.View.WorldRenderXna.Zoom(Int32 direction)
   at TEditXna.View.WorldRenderXna.xnaViewport_HwndMouseWheel(Object sender, HwndMouseEventArgs e)
   at TEdit.UI.Xaml.XnaContentHost.GraphicsDeviceControl.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndHost.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at TEditXna.App.Main() 

I really have no idea what to do

**Comment by CyberZHG** [comment]
v3.5.14228.27 is only compatible with Terraria 1.2.4.
You should try a newer one: [TEdit](https://dl.dropboxusercontent.com/u/21952217/TEdit%20(fromSource).zip)

**Comment by BinaryConstruct** [comment]
Official download url: http://www.binaryconstruct.com/downloads/
