### ISSUE TITLE
tEdit won't open 

### ISSUE THREAD

**Issue by Indigy** [TEdit/Terraria-Map-Editor#663]
```
08-24-2015 21:43: Starting TEdit 3.6.150812.0114 
08-24-2015 21:43: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
08-24-2015 21:43: Failed to verify Terraria Paths. TEdit may not run properly. 
08-24-2015 21:43: Error - Root element is missing.
   at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Configuration.XmlUtil..ctor(Stream stream, String name, Boolean readToFirstElement, ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile() 
08-24-2015 21:43: Error - Root element is missing. (C:\Users\Jack\AppData\Local\TEditXna\TEditXna.exe_Url_hvxsxpp3ke4glfpars1bckjpj0szbrzl\3.6.0.0\user.config)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e) 
08-24-2015 21:43: Error - Configuration system failed to initialize
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
   at System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(String configPath, BaseConfigurationRecord configRecord)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   at System.Configuration.SettingsBase.get_Item(String propertyName)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at TEditXna.DependencyChecker.CheckPaths() in C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\DependencyChecker.cs:line 17
   at TEditXna.App.OnStartup(StartupEventArgs e) in C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\App.xaml.cs:line 52 
08-24-2015 21:43: Unable to locate Terraria. No texture data will be available. 
08-24-2015 21:44: Error - Root element is missing.
   at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Configuration.XmlUtil..ctor(Stream stream, String name, Boolean readToFirstElement, ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile() 
08-24-2015 21:44: Error - Root element is missing. (C:\Users\Jack\AppData\Local\TEditXna\TEditXna.exe_Url_hvxsxpp3ke4glfpars1bckjpj0szbrzl\3.6.0.0\user.config)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e) 
08-24-2015 21:44: Error - Configuration system failed to initialize
   at System.Configuration.ConfigurationManager.RefreshSection(String sectionName)
   at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   at System.Configuration.SettingsBase.get_Item(String propertyName)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at TEditXna.ViewModel.WorldViewModel..ctor() in C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\ViewModel\WorldViewModel.cs:line 94
   at TEditXna.ViewModel.ViewModelLocator.CreateWorldViewModel() in C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\ViewModel\ViewModelLocator.cs:line 31
   at TEditXna.ViewModel.ViewModelLocator..cctor() in C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\ViewModel\ViewModelLocator.cs:line 13 
08-24-2015 21:44: Error - The type initializer for 'TEditXna.ViewModel.ViewModelLocator' threw an exception.
   at TEditXna.ViewModel.ViewModelLocator.get_WorldViewModel()
   at TEditXna.View.WorldRenderXna..ctor() in C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\View\WorldRenderXna.xaml.cs:line 65 
08-24-2015 21:44: Error - The invocation of the constructor on type 'TEditXna.View.WorldRenderXna' that matches the specified binding constraints threw an exception.
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at TEditXna.App.Main() in C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\obj\Release\App.g.cs:line 0 
```

**Comment by enigmaquip** [comment]
Make sure you have .NET 4.5 installed, the new beta does require a higher version of .net

https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements

**Comment by Indigy** [comment]
I got this stuff installed already,problem is that it worked before but now it does not

**Comment by Berserker66** [comment]
you config file appears corrupted.
Delete the file mentioned in this line:
08-24-2015 21:44: Error - Root element is missing. (C:\Users\Jack\AppData\Local\TEditXna\TEditXna.exe_Url_hvxsxpp3ke4glfpars1bckjpj0szbrzl\3.6.0.0\user.config)

**Comment by BinaryConstruct** [comment]
@Berserker66 comment should resolve your issue. If not, please reopen this issue.

**Comment by lewisbraden** [comment]
03-21-2017 14:48:52: Starting TEdit 3.9.16350.0618 
03-21-2017 14:48:52: OS: Microsoft Windows NT 6.2.9200.0 
03-21-2017 14:48:52: Terraria v1.3.4.4 
03-21-2017 14:48:52: Terraria Data Path: C:\Program Files (x86)\Steam\steamapps\common\Terraria\Content 
03-21-2017 14:48:53: Creating Undo cache: C:\Users\lewis\AppData\Roaming\TEdit\undo_908041447

**Comment by lewisbraden** [comment]
im having the same issue except mine says that
