### ISSUE TITLE
Error on loading world

### ISSUE THREAD

**Issue by null0000** [TEdit/Terraria-Map-Editor#673]
Few things:

* The version number is wrong. It's 3.6.1544.0302
* TEdit doesn't successfully start when I try running it again until I reboot windows.
* The world I'm trying to load is corrupt, so there's a good chance this is spurious.

09-01-2015 19:10: Starting TEdit 3.6.150812.0114 
09-01-2015 19:10: OS: Microsoft Windows NT 6.2.9200.0 
09-01-2015 19:10: Terraria Data Path: c:/program files (x86)/steam\steamapps\common\terraria\Content 
09-01-2015 19:10: Creating Undo cache: C:\Users\Nah\AppData\Roaming\TEdit\undo_556211599 
09-01-2015 19:11: Error - Object reference not set to an instance of an object.
   at TEditXna.View.WorldRenderXna.DrawSprites() in C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\View\WorldRenderXna.xaml.cs:line 452
   at TEditXna.View.WorldRenderXna.Render(GraphicsDeviceEventArgs e) in C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\View\WorldRenderXna.xaml.cs:line 356
   at TEditXna.View.WorldRenderXna.xnaViewport_RenderXna(Object sender, GraphicsDeviceEventArgs e) in C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\View\WorldRenderXna.xaml.cs:line 281
   at TEdit.UI.Xaml.XnaContentHost.GraphicsDeviceControl.CompositionTarget_Rendering(Object sender, EventArgs e) in C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\UI\Xaml\XnaContentHost\GraphicsDeviceControl.cs:line 325
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at TEditXna.App.Main() in C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\obj\Release\App.g.cs:line 0

**Comment by enigmaquip** [comment]
Throw up your world somewhere, I'd love to take a look at it
