### ISSUE TITLE
Possible conflict opening TEdit too soon after closing Terraria

### ISSUE THREAD

**Issue by Mystil** [TEdit/Terraria-Map-Editor#690]
10-04-2015 12:57: Starting TEdit 3.6.150812.0114 
10-04-2015 12:57: OS: Microsoft Windows NT 6.2.9200.0 
10-04-2015 12:57: Terraria Data Path: d:/steam\steamapps\common\terraria\Content 
10-04-2015 12:57: Creating Undo cache: C:\Users\Mystil.Paramount\AppData\Roaming\TEdit\undo_292638375 
10-04-2015 12:57: Error - The process cannot access the file 'C:\Users\Mystil.Paramount\AppData\Roaming\TEdit\undo_292638375\undo_temp_0' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at TEditXna.Editor.Undo.UndoBuffer..ctor(String fileName) in C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\Editor\Undo\UndoBuffer.cs:line 21
   at TEditXna.Editor.Undo.UndoManager..ctor(WorldViewModel viewModel) in C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\Editor\Undo\UndoManager.cs:line 137
   at TEditXna.ViewModel.WorldViewModel..ctor() in C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\ViewModel\WorldViewModel.cs:line 105
   at TEditXna.ViewModel.ViewModelLocator.CreateWorldViewModel() in C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\ViewModel\ViewModelLocator.cs:line 31
   at TEditXna.ViewModel.ViewModelLocator..cctor() in C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\ViewModel\ViewModelLocator.cs:line 13 
10-04-2015 12:57: Error - The type initializer for 'TEditXna.ViewModel.ViewModelLocator' threw an exception.
   at TEditXna.ViewModel.ViewModelLocator.get_WorldViewModel()
   at TEditXna.View.WorldRenderXna..ctor() in C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\View\WorldRenderXna.xaml.cs:line 66 
10-04-2015 12:57: Error - The invocation of the constructor on type 'TEditXna.View.WorldRenderXna' that matches the specified binding constraints threw an exception.
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<_ctor>b__0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at TEditXna.App.Main() in C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\obj\Release\App.g.cs:line 0 
10-04-2015 12:57: Removing undo cache: C:\Users\Mystil.Paramount\AppData\Roaming\TEdit\undo_292638375 
10-04-2015 12:57: Error - The process cannot access the file 'undo_temp_0' because it is being used by another process.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at TEditXna.Editor.Undo.UndoManager.CleanupOldUndoFiles(Boolean forceCleanup) in C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\Editor\Undo\UndoManager.cs:line 88

**Comment by enigmaquip** [comment]
Did you have more than one copy of tedit open? The error was in the undo file it creates on load, it couldn't access it. It wouldn't have any relation to having Terraria open. If you are still having issues try deleting the directory at C:\Users\Mystil.Paramount\AppData\Roaming\TEdit\undo_292638375
