### ISSUE TITLE
Crash when reading tally

### ISSUE THREAD

**Issue by icdragn** [TEdit/Terraria-Map-Editor#720]
I'm running Tedit version v3.6.15327.2018 on Windows 7 Pro. I can successfully open a world, but when I click over to the "Tally" tab and click the "Read" button, Tedit crashes. Here is the log file:

11-28-2015 18:25: Starting TEdit 3.6.150812.0114 
11-28-2015 18:25: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
11-28-2015 18:25: Terraria Data Path: C:\GOG Games\Terraria\Content 
11-28-2015 18:25: Creating Undo cache: C:\Users\David\AppData\Roaming\TEdit\undo_305635952 
11-28-2015 18:25: Error - Arithmetic operation resulted in an overflow.
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) in C:\a\1\s\TEditXna\View\WorldRenderXna.xaml.cs:line 249 
11-28-2015 18:25: Error - Arithmetic operation resulted in an overflow.
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) in C:\a\1\s\TEditXna\View\WorldRenderXna.xaml.cs:line 249 
11-28-2015 18:25: Error - Arithmetic operation resulted in an overflow.
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) in C:\a\1\s\TEditXna\View\WorldRenderXna.xaml.cs:line 249 
11-28-2015 18:25: Error - Arithmetic operation resulted in an overflow.
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) in C:\a\1\s\TEditXna\View\WorldRenderXna.xaml.cs:line 249 
11-28-2015 18:25: Error - Arithmetic operation resulted in an overflow.
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) in C:\a\1\s\TEditXna\View\WorldRenderXna.xaml.cs:line 249 
11-28-2015 18:25: Error - Arithmetic operation resulted in an overflow.
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) in C:\a\1\s\TEditXna\View\WorldRenderXna.xaml.cs:line 249 
11-28-2015 18:25: Error - Arithmetic operation resulted in an overflow.
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) in C:\a\1\s\TEditXna\View\WorldRenderXna.xaml.cs:line 249 
11-28-2015 18:25: Error - Arithmetic operation resulted in an overflow.
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) in C:\a\1\s\TEditXna\View\WorldRenderXna.xaml.cs:line 249 
11-28-2015 18:25: Error - Arithmetic operation resulted in an overflow.
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) in C:\a\1\s\TEditXna\View\WorldRenderXna.xaml.cs:line 249 
11-28-2015 18:25: Error - Arithmetic operation resulted in an overflow.
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) in C:\a\1\s\TEditXna\View\WorldRenderXna.xaml.cs:line 249 
11-28-2015 18:25: Error - Arithmetic operation resulted in an overflow.
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) in C:\a\1\s\TEditXna\View\WorldRenderXna.xaml.cs:line 249 
11-28-2015 18:25: Error - Arithmetic operation resulted in an overflow.
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) in C:\a\1\s\TEditXna\View\WorldRenderXna.xaml.cs:line 249 
11-28-2015 18:25: Error - Cannot access a closed Stream.
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at TEditXNA.Terraria.KillTally.LoadTally(World world) in C:\a\1\s\TEditXna\Terraria\KillTally.cs:line 38
   at TEditXna.ViewModel.WorldViewModel.GetTallyCount() in C:\a\1\s\TEditXna\ViewModel\WorldViewModel.cs:line 622 
11-28-2015 18:25: Error - Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at TEditXna.App.Main() in C:\a\1\s\TEditXna\obj\Release\App.g.cs:line 0 

Up until now, I have been using version 3.6.15266.1907 with no problems in this area. Is anyone else seeing this same issue?

Thank you for this great program!

**Comment by icdragn** [comment]
I got some time tonight to try versions of Tedit between 3.6.15266.1907 and 3.6.15327.2018. It looks like the last version of Tedit that can successfully read tallies is 3.6.15293.2023. After that version, all fail with the error I reported above.

**Comment by enigmaquip** [comment]
Fixed, thanks for your help, should be updated in the newest build available today

**Comment by icdragn** [comment]
I just downloaded v3.6.15341.1609 and reading the tally does not cause a crash now. Thank you for the fix!
