### ISSUE TITLE
World Version 146

### ISSUE THREAD

**Issue by Chiy1001** [TEdit/Terraria-Map-Editor#722]
I've been downloading lots of versions... but none of them opens this world. Is it a fixable issue?

World File Error
---------------------------
There was an error reading the world file, do you wish to force it to load anyway?

WARNING: This may have unexpected results including corrupt world files and program crashes.

The error is :

TEdit supports world files of version 102.

This world is Version 146.

System.IO.EndOfStreamException: Unable to read beyond the end of the stream.

   at System.IO.BinaryReader.ReadString()

   at TEditXNA.Terraria.World.LoadHeaderFlags(BinaryReader r, World w, Int32 expectedPosition) in C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\Terraria\World.FileV2.cs:line 1139

   at TEditXNA.Terraria.World.LoadV2(BinaryReader b, String filename, World w) in C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\Terraria\World.FileV2.cs:line 616

   at TEditXNA.Terraria.World.LoadWorld(String filename) in C:\a\1af8616d\TEdit\Terraria-Map-Editor\TEditXna\Terraria\World.cs:line 112
---------------------------

**Comment by tanpro260196** [comment]
Could post that world here? That will be easier to reproduce the problem.

**Comment by enigmaquip** [comment]
feel free to upload your world file to drop box and post a link and I'll take a look at it

**Comment by enigmaquip** [comment]
Just by a quick glance it doesn't seem like you're using one of the latest Betas though, as the error should say TEdit supports world files of version 156.

**Comment by Chiy1001** [comment]
@enigmaquip using the latest one, the error is the same, but does says that; version 156. Anyway I'm using 1.3.0.1.

**Comment by BinaryConstruct** [comment]
Please try the latest beta versions.
