### ISSUE TITLE
Issue with editing maps (Crashes when trying to edit).

### ISSUE THREAD

**Issue by ShadowofChernobyl** [TEdit/Terraria-Map-Editor#733]
01-08-2016 21:00: Starting TEdit 3.6.150812.0114 
01-08-2016 21:00: OS: Microsoft Windows NT 6.0.6002 Service Pack 2 
01-08-2016 21:00: DirectX 10 unsupported. DirectX 11 or higher is required. 
01-08-2016 21:00: Terraria Data Path: c:/program files (x86)/steam\steamapps\common\terraria\Content 
01-08-2016 21:00: Creating Undo cache: C:\Users\LOL_nicetry\AppData\Roaming\TEdit\undo_737703262 
01-08-2016 21:00: Error - Object reference not set to an instance of an object.
   at TEditXna.View.WorldRenderXna.UpdatePreview() in C:\a\1\s\TEditXna\View\WorldRenderXna.xaml.cs:line 135 
01-08-2016 21:00: Error - Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at GalaSoft.MvvmLight.Command.RelayCommand`1.Execute(Object parameter) in c:\MvvmLight\Source\GalaSoft.MvvmLight\GalaSoft.MvvmLight (PCL)\Command\RelayCommandGeneric.cs:line 238
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at TEditXna.App.Main() in C:\a\1\s\TEditXna\obj\Release\App.g.cs:line 0

**Comment by ShadowofChernobyl** [comment]
It also has V0.0.0.0 as the title of window, and says to check for new update.

**Comment by KenAlin** [comment]
Hi there,

```
01-08-2016 21:00: DirectX 10 unsupported. DirectX 11 or higher is required. 
```

Unfortunately, TEdit require DirectX 11. Please update your version of DirectX.
As for the `V0.0.0.0` in the title, that's normal.

**Comment by eXXOtaku** [comment]
Yupp, your DirectX isn`t supported, at least. 
Unfortunately u have to Install an OS with 6.1 that means you need Windows 7 and
a DirectX 11 supported graphics card. Windows Vista doesn't support DirectX 11 so far as I know.

**Comment by ShadowofChernobyl** [comment]
Alright, thanks. I'll see what I can do about getting windows 7.
