### ISSUE TITLE
Error Loading Corrupt World

### ISSUE THREAD

**Issue by terrariaworldproblem** [TEdit/Terraria-Map-Editor#755]
My world recently went corrupt, it loads fine the the online Terraria Map viewer, but not with Tedit.

Gives this error code upon attempting to load it, or gets stuck with "calculating colors" in the corner.

World located [here](https://drive.google.com/file/d/0B6xPB-LjRHo4QUxNX09yeDNpb1k/view?usp=sharing).

03-24-2016 19:37:58: Starting TEdit 3.6.16071.2036 
03-24-2016 19:37:58: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
03-24-2016 19:37:59: Terraria Data Path: c:/program files (x86)/steam\steamapps\common\terraria\Content 
03-24-2016 19:37:59: Creating Undo cache: C:\Users\Chris\AppData\Roaming\TEdit\undo_345884843 
03-24-2016 19:39:41: Error - Object reference not set to an instance of an object.
   at TEditXna.View.WorldRenderXna.DrawSprites() in c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:line 455
   at TEditXna.View.WorldRenderXna.Render(GraphicsDeviceEventArgs e) in c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:line 359
   at TEditXna.View.WorldRenderXna.xnaViewport_RenderXna(Object sender, GraphicsDeviceEventArgs e) in c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:line 284
   at TEdit.UI.Xaml.XnaContentHost.GraphicsDeviceControl.CompositionTarget_Rendering(Object sender, EventArgs e) in c:\projects\terraria-map-editor\TEditXna\UI\Xaml\XnaContentHost\GraphicsDeviceControl.cs:line 325
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at TEditXna.App.Main() in c:\projects\terraria-map-editor\TEditXna\obj\Release\App.g.cs:line 0

**Comment by enigmaquip** [comment]
Yea TEdit does checks that a file is complete when loading and due to your corruption somewhere in the tile data it just goes to zeros, so your save file has no chest data, no sign data, no npc data.... and because it's got incomplete tile data it causes a hang in the loading process when you tell it to load anyways

**Comment by BinaryConstruct** [comment]
```
03-24-2016 19:37:58: Starting TEdit 3.6.16071.2036 
03-24-2016 19:37:58: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
03-24-2016 19:37:59: Terraria Data Path: c:/program files (x86)/steam\steamapps\common\terraria\Content 
03-24-2016 19:37:59: Creating Undo cache: C:\Users\Chris\AppData\Roaming\TEdit\undo_345884843 
03-24-2016 19:39:41: Error - Object reference not set to an instance of an object.
   at TEditXna.View.WorldRenderXna.DrawSprites() in c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:line 455
   at TEditXna.View.WorldRenderXna.Render(GraphicsDeviceEventArgs e) in c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:line 359
   at TEditXna.View.WorldRenderXna.xnaViewport_RenderXna(Object sender, GraphicsDeviceEventArgs e) in c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:line 284
   at TEdit.UI.Xaml.XnaContentHost.GraphicsDeviceControl.CompositionTarget_Rendering(Object sender, EventArgs e) in c:\projects\terraria-map-editor\TEditXna\UI\Xaml\XnaContentHost\GraphicsDeviceControl.cs:line 325
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at TEditXna.App.Main() in c:\projects\terraria-map-editor\TEditXna\obj\Release\App.g.cs:line 0 
```
