### ISSUE TITLE
crash log

### ISSUE THREAD

**Issue by goodboy10** [TEdit/Terraria-Map-Editor#758]
03-29-2016 18:03: Starting TEdit 3.5.15047.30 
03-29-2016 18:03: OS: Microsoft Windows NT 6.2.9200.0 
03-29-2016 18:03: .Net >= 4.0 
03-29-2016 18:03: XNA 4.0 
03-29-2016 18:03: Terraria Data Path: c:/program files (x86)/steam\steamapps\common\terraria\Content 
03-29-2016 18:03: Creating Undo cache: C:\Users\Jeffery\AppData\Roaming\TEdit\undo_839928759 
03-29-2016 18:03: Error - This method does not accept null for this parameter.
Parameter name: data
   at Microsoft.Xna.Framework.Graphics.Texture2D.CopyData[T](Int32 level, Nullable`1 rect, T[] data, Int32 startIndex, Int32 elementCount, UInt32 options, Boolean isSetting)
   at Microsoft.Xna.Framework.Graphics.Texture2D.GetData[T](Int32 level, Nullable`1 rect, T[] data, Int32 startIndex, Int32 elementCount)
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 
03-29-2016 18:03: Error - Arithmetic operation resulted in an overflow.
   at TEditXna.View.WorldRenderXna.LoadTerrariaTextures(GraphicsDeviceEventArgs e) 
03-29-2016 18:08: Error - Index was outside the bounds of the array.
   at TEditXNA.Terraria.World.SerializeTileData(Tile tile, Int32& dataIndex, Int32& headerIndex)
   at TEditXna.Editor.Undo.UndoBuffer.Flush()
   at TEditXna.Editor.Undo.UndoBuffer.Close()
   at TEditXna.Editor.Undo.UndoManager.SaveUndo()
   at TEditXna.Editor.Tools.PencilTool.MouseUp(TileMouseState e)
   at TEditXna.ViewModel.WorldViewModel.MouseUpTile(TileMouseState e)
   at TEditXna.View.WorldRenderXna.xnaViewport_HwndLButtonUp(Object sender, HwndMouseEventArgs e)
   at TEdit.UI.Xaml.XnaContentHost.GraphicsDeviceControl.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndHost.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at TEditXna.App.Main()

**Comment by goodboy10** [comment]
Can Some One Please Help Me With This

**Comment by enigmaquip** [comment]
Wow you need to have patience. You have a better chance of being helped if you actually described your problem and what steps you took to get there instead of just blindly posting a crash log.

**Comment by goodboy10** [comment]
all i did was open TEdit and this showed up

**Comment by BinaryConstruct** [comment]
v3.5.15047.30 is older and known to have issues with undo causing crashes. Please use an updated beta version.

**Comment by goodboy10** [comment]
k
