### ISSUE TITLE
Replace Image "pack" in XAML with StreamReader

### ISSUE THREAD

**Issue by TsunamidaShirakawa** [TEdit/Terraria-Map-Editor#766]
```
04-15-2016 10:46: Starting TEdit 3.5.15047.30 
04-15-2016 10:46: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
04-15-2016 10:46: .Net >= 4.0 
04-15-2016 10:46: XNA 4.0 
04-15-2016 10:46: Terraria Data Path: C:\Program Files (x86)\Steam\steamapps\common\Terraria\Content 
04-15-2016 10:46: Creating Undo cache: C:\Users\TsunamidaSK\AppData\Roaming\TEdit\undo_343955341 
04-15-2016 10:46: Error - ContentType string is not valid. Expected format is type/subtype.
   at MS.Internal.ContentType.ParseTypeAndSubType(String typeAndSubType)
   at MS.Internal.ContentType..ctor(String contentType)
   at MS.Internal.MimeTypeMapper.GetMimeTypeFromUrlMon(Uri uriSource)
   at MS.Internal.MimeTypeMapper.GetMimeTypeFromUri(Uri uriSource)
   at MS.Internal.AppModel.ResourcePart.GetContentTypeCore()
   at System.IO.Packaging.PackagePart.get_ContentType()
   at MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)
   at System.IO.Packaging.PackagePart.GetStream(FileMode mode, FileAccess access)
   at System.IO.Packaging.PackWebResponse.CachedResponse.GetResponseStream()
   at System.IO.Packaging.PackWebResponse.GetResponseStream()
   at System.IO.Packaging.PackWebResponse.get_ContentType()
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at System.Windows.Media.Imaging.BitmapImage..ctor(Uri uriSource, RequestCachePolicy uriCachePolicy)
   at TEditXna.Editor.Tools.PasteTool..ctor(WorldViewModel worldViewModel)
   at TEditXna.ViewModel.ViewModelLocator.CreateWorldViewModel()
   at TEditXna.ViewModel.ViewModelLocator..cctor() 
04-15-2016 10:46: Error - The type initializer for 'TEditXna.ViewModel.ViewModelLocator' threw an exception.
   at TEditXna.ViewModel.ViewModelLocator.get_WorldViewModel()
   at TEditXna.View.WorldRenderXna..ctor() 
04-15-2016 10:46: Error - The invocation of the constructor on type 'TEditXna.View.WorldRenderXna' that matches the specified binding constraints threw an exception.
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<_ctor>b__0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at TEditXna.App.Main() 

on windows 7, running as admin, took ownership of everything even though it was probably a moot point, i dunno' what to do here.
```

**Comment by KenAlin** [comment]
Please update your TEdit version : http://www.binaryconstruct.com/downloads/

**Comment by TsunamidaShirakawa** [comment]
should've said i already tried that, i was hopping versions to see if anything'd change


04-16-2016 12:19:09: Starting TEdit 3.6.16071.2036 
04-16-2016 12:19:09: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
04-16-2016 12:19:09: Terraria Data Path: c:/program files (x86)/steam\steamapps\common\terraria\Content 
04-16-2016 12:19:09: Creating Undo cache: C:\Users\TsunamidaSK\AppData\Roaming\TEdit\undo_193588704 
04-16-2016 12:19:09: Error - ContentType string is not valid. Expected format is type/subtype.
   at MS.Internal.ContentType.ParseTypeAndSubType(String typeAndSubType)
   at MS.Internal.ContentType..ctor(String contentType)
   at MS.Internal.MimeTypeMapper.GetMimeTypeFromUrlMon(Uri uriSource)
   at MS.Internal.MimeTypeMapper.GetMimeTypeFromUri(Uri uriSource)
   at MS.Internal.AppModel.ResourcePart.GetContentTypeCore()
   at System.IO.Packaging.PackagePart.get_ContentType()
   at MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)
   at System.IO.Packaging.PackagePart.GetStream(FileMode mode, FileAccess access)
   at System.IO.Packaging.PackWebResponse.CachedResponse.GetResponseStream()
   at System.IO.Packaging.PackWebResponse.get_ContentType()
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at TEditXna.Editor.Tools.PasteTool..ctor(WorldViewModel worldViewModel) in c:\projects\terraria-map-editor\TEditXna\Editor\Tools\PasteTool.cs:line 17
   at TEditXna.ViewModel.ViewModelLocator.CreateWorldViewModel() in c:\projects\terraria-map-editor\TEditXna\ViewModel\ViewModelLocator.cs:line 32
   at TEditXna.ViewModel.ViewModelLocator..cctor() in c:\projects\terraria-map-editor\TEditXna\ViewModel\ViewModelLocator.cs:line 13 
04-16-2016 12:19:09: Error - The type initializer for 'TEditXna.ViewModel.ViewModelLocator' threw an exception.
   at TEditXna.ViewModel.ViewModelLocator.get_WorldViewModel()
   at TEditXna.View.WorldRenderXna..ctor() in c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:line 67 
04-16-2016 12:19:09: Error - The invocation of the constructor on type 'TEditXna.View.WorldRenderXna' that matches the specified binding constraints threw an exception.
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<_ctor>b__0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at TEditXna.App.Main() in c:\projects\terraria-map-editor\TEditXna\obj\Release\App.g.cs:line 0

**Comment by BinaryConstruct** [comment]
Please try 3.7 beta.

**Comment by TsunamidaShirakawa** [comment]
done

05-23-2016 20:44:17: Starting TEdit 3.7.16144.2135 
05-23-2016 20:44:17: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
05-23-2016 20:44:17: Terraria Data Path: C:\Program Files (x86)\Steam\steamapps\common\Terraria\Content 
05-23-2016 20:44:17: Creating Undo cache: C:\Users\TsunamidaSK\AppData\Roaming\TEdit\undo_360285098 
05-23-2016 20:44:17: Error - ContentType string is not valid. Expected format is type/subtype.
   at MS.Internal.ContentType.ParseTypeAndSubType(String typeAndSubType)
   at MS.Internal.ContentType..ctor(String contentType)
   at MS.Internal.MimeTypeMapper.GetMimeTypeFromUrlMon(Uri uriSource)
   at MS.Internal.MimeTypeMapper.GetMimeTypeFromUri(Uri uriSource)
   at MS.Internal.AppModel.ResourcePart.GetContentTypeCore()
   at System.IO.Packaging.PackagePart.get_ContentType()
   at MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)
   at System.IO.Packaging.PackagePart.GetStream(FileMode mode, FileAccess access)
   at System.IO.Packaging.PackWebResponse.CachedResponse.GetResponseStream()
   at System.IO.Packaging.PackWebResponse.get_ContentType()
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at TEditXna.Editor.Tools.PasteTool..ctor(WorldViewModel worldViewModel) in c:\projects\terraria-map-editor\TEditXna\Editor\Tools\PasteTool.cs:line 17
   at TEditXna.ViewModel.ViewModelLocator.CreateWorldViewModel() in c:\projects\terraria-map-editor\TEditXna\ViewModel\ViewModelLocator.cs:line 32
   at TEditXna.ViewModel.ViewModelLocator..cctor() in c:\projects\terraria-map-editor\TEditXna\ViewModel\ViewModelLocator.cs:line 13 
05-23-2016 20:44:17: Error - The type initializer for 'TEditXna.ViewModel.ViewModelLocator' threw an exception.
   at TEditXna.ViewModel.ViewModelLocator.get_WorldViewModel()
   at TEditXna.View.WorldRenderXna..ctor() in c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:line 67 
05-23-2016 20:44:17: Error - The invocation of the constructor on type 'TEditXna.View.WorldRenderXna' that matches the specified binding constraints threw an exception.
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<_ctor>b__0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at TEditXna.App.Main() in c:\projects\terraria-map-editor\TEditXna\obj\Release\App.g.cs:line 0

idk, man. wish i did.

**Comment by BinaryConstruct** [comment]
Can you please try reinstalling .net framework and directx?  Even if you have the latest version, a reinstall may be required.

DirectX - https://support.microsoft.com/en-us/kb/179113
.Net 

https://www.microsoft.com/en-us/download/details.aspx?id=49981

**Comment by TsunamidaShirakawa** [comment]
```
> 06-07-2016 23:28:12: Starting TEdit 3.6.16071.2036 
06-07-2016 23:28:12: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
06-07-2016 23:28:12: Terraria Data Path: C:\Program Files (x86)\Steam\steamapps\common\Terraria\Content 
06-07-2016 23:28:13: Creating Undo cache: C:\Users\TsunamidaSK\AppData\Roaming\TEdit\undo_155823049 
06-07-2016 23:28:13: Error - ContentType string is not valid. Expected format is type/subtype.
   at MS.Internal.ContentType.ParseTypeAndSubType(String typeAndSubType)
   at MS.Internal.ContentType..ctor(String contentType)
   at MS.Internal.MimeTypeMapper.GetMimeTypeFromUrlMon(Uri uriSource)
   at MS.Internal.MimeTypeMapper.GetMimeTypeFromUri(Uri uriSource)
   at MS.Internal.AppModel.ResourcePart.GetContentTypeCore()
   at System.IO.Packaging.PackagePart.get_ContentType()
   at MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)
   at System.IO.Packaging.PackagePart.GetStream(FileMode mode, FileAccess access)
   at System.IO.Packaging.PackWebResponse.CachedResponse.GetResponseStream()
   at System.IO.Packaging.PackWebResponse.get_ContentType()
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at TEditXna.Editor.Tools.PasteTool..ctor(WorldViewModel worldViewModel) in c:\projects\terraria-map-editor\TEditXna\Editor\Tools\PasteTool.cs:line 17
   at TEditXna.ViewModel.ViewModelLocator.CreateWorldViewModel() in c:\projects\terraria-map-editor\TEditXna\ViewModel\ViewModelLocator.cs:line 32
   at TEditXna.ViewModel.ViewModelLocator..cctor() in c:\projects\terraria-map-editor\TEditXna\ViewModel\ViewModelLocator.cs:line 13 
06-07-2016 23:28:13: Error - The type initializer for 'TEditXna.ViewModel.ViewModelLocator' threw an exception.
   at TEditXna.ViewModel.ViewModelLocator.get_WorldViewModel()
   at TEditXna.View.WorldRenderXna..ctor() in c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:line 67 
06-07-2016 23:28:13: Error - The invocation of the constructor on type 'TEditXna.View.WorldRenderXna' that matches the specified binding constraints threw an exception.
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at TEditXna.App.Main() in c:\projects\terraria-map-editor\TEditXna\obj\Release\App.g.cs:line 0

**Comment by BinaryConstruct** [comment]
https://github.com/TEdit/Terraria-Map-Editor/blob/master/TEditXna/Editor/Tools/PasteTool.cs#L17

**Comment by enigmaquip** [comment]
This is just the first tool to be loaded in by ViewModelLocator, I would assume if you swapped the order of the tools, it would crap out on whatever is first. Seems that this particular computer doesn't like the png format. With some cursory searching yesterday I found some people commenting on possibly the mime type of png's being changed in the registry by certain 3d party image editing programs and causing crashes in WPF

**Comment by BinaryConstruct** [comment]
Maybe add a resource reader, something like this?
```csharp

        private static BitmapImage ReadImageResource(string resourceName, Assembly assembly = null)
        {
            if (assembly == null)
                assembly = Assembly.GetExecutingAssembly();
            //var resourceName = "AssemblyName.MyFile.txt";

            using (Stream stream = assembly.GetManifestResourceStream(resourceName))
            {
                var bitmapImage = new System.Windows.Media.Imaging.BitmapImage();
                bitmapImage.BeginInit();
                bitmapImage.StreamSource = stream;
                bitmapImage.EndInit();
                return bitmapImage;
            }
        }
```
