### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by glitch159** [TEdit/Terraria-Map-Editor#778]
I was told to put this in the issues list, so here you are:
-----------------------------------------------------------------------------------------------------------------------
```
05-22-2016 13:41:24: Starting TEdit 3.6.16126.1508 
05-22-2016 13:41:24: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
05-22-2016 13:41:24: Terraria Data Path: c:/program files (x86)/steam\steamapps\common\terraria\Content 
05-22-2016 13:41:25: Creating Undo cache: C:\Users\Matt\AppData\Roaming\TEdit\undo_503895531 
05-22-2016 13:45:14: Error - Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at TEditXna.View.WorldRenderXna.DrawSprites() in c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:line 1255
   at TEditXna.View.WorldRenderXna.Render(GraphicsDeviceEventArgs e) in c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:line 361
   at TEditXna.View.WorldRenderXna.xnaViewport_RenderXna(Object sender, GraphicsDeviceEventArgs e) in c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:line 285
   at TEdit.UI.Xaml.XnaContentHost.GraphicsDeviceControl.CompositionTarget_Rendering(Object sender, EventArgs e) in c:\projects\terraria-map-editor\TEditXna\UI\Xaml\XnaContentHost\GraphicsDeviceControl.cs:line 328
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at TEditXna.App.Main() in c:\projects\terraria-map-editor\TEditXna\obj\Release\App.g.cs:line 0 
```

**Comment by BinaryConstruct** [comment]
Thank you, can you please try the 3.7 beta and see if there is any improvement?

**Comment by glitch159** [comment]
Ok, will do :) the reason i wasnt using the most recent version was because when you zoom in on the world to the point where it should show the textures of things (like blocks and walls and sprites, etc.) it doesnt, and i disliked that so i stuck with my old version so i could see things in detail when i zoomed in. Ill test things out in the newest release and reply when i have/havent noticed improvement.
