### ISSUE TITLE
Cannot start tedit

### ISSUE THREAD

**Issue by Vargrey** [TEdit/Terraria-Map-Editor#864]
I've read around here and can't find a solution for my problem, none of the ways to fix it that i've seen have worked. i've tried different verisions of tedit and even moved the terraria install to the C drive. as it was installed on the d drive before.

08-05-2016 21.41.32: Starting TEdit 3.8.16218.0906 
08-05-2016 21.41.32: OS: Microsoft Windows NT 6.2.9200.0 
08-05-2016 21.41.32: Failed to verify Terraria Paths. TEdit may not run properly. 
08-05-2016 21.41.32: Error - Input string was not in a correct format.
   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Convert.ToSingle(String value)
   at TEditXNA.Terraria.World.LoadObjectDbXml(String file) in c:\projects\terraria-map-editor\TEditXna\Terraria\World.Settings.cs:line 271
   at TEditXNA.Terraria.World..cctor() in c:\projects\terraria-map-editor\TEditXna\Terraria\World.Settings.cs:line 52 
08-05-2016 21.41.32: Error - The type initializer for 'TEditXNA.Terraria.World' threw an exception.
   at TEditXna.DependencyChecker.CheckPaths() in c:\projects\terraria-map-editor\TEditXna\DependencyChecker.cs:line 20
   at TEditXna.App.OnStartup(StartupEventArgs e) in c:\projects\terraria-map-editor\TEditXna\App.xaml.cs:line 52 
08-05-2016 21.41.32: Unable to locate Terraria. No texture data will be available. 
08-05-2016 21.41.32: Error - Input string was not in a correct format.
   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Convert.ToSingle(String value)
   at TEditXNA.Terraria.World.LoadObjectDbXml(String file) in c:\projects\terraria-map-editor\TEditXna\Terraria\World.Settings.cs:line 271
   at TEditXNA.Terraria.World..cctor() in c:\projects\terraria-map-editor\TEditXna\Terraria\World.Settings.cs:line 52 
08-05-2016 21.41.32: Error - The type initializer for 'TEditXNA.Terraria.World' threw an exception.
   at TEditXNA.Terraria.World.get_TileBricks() 
08-05-2016 21.41.32: Error - Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Windows.Markup.StaticExtension.GetFieldOrPropertyValue(Type type, String name, Object& value)
   at System.Windows.Markup.StaticExtension.ProvideValue(IServiceProvider serviceProvider)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider) 
08-05-2016 21.41.32: Error - Provide value on 'System.Windows.Markup.StaticExtension' threw an exception.
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at TEditXna.App.Main() in c:\projects\terraria-map-editor\TEditXna\obj\Release\App.g.cs:line 0

**Comment by enigmaquip** [comment]
You are extracting all the files from the zip file yes?

**Comment by Vargrey** [comment]
Yeah, i've been trying differet things fo awhile now and just got it working a minute ago, for some reason a version from july 23 works. so... Solved i guess.

**Comment by enigmaquip** [comment]
so no versions after july 23 work?

**Comment by enigmaquip** [comment]
I'm going to guess that 3.8.16217.122 is the cut off, before works but after doesn't? that's when the code was added that's called out in that error.

**Comment by Vargrey** [comment]
I skipped around a bit, but none from august worked. This one was just the first one I found. so maybe some a bit later worked, give me a few minuttes and i'll test it.

**Comment by Vargrey** [comment]
Seems i was wrong, TEdit3_BETA_v3.8.16214.120.zip from august 1 workes. So something added after that is the cause.

**Comment by enigmaquip** [comment]
When the next build pops up here in a few mins will you give it a try and see if it fixes the issue

**Comment by Vargrey** [comment]
Will do.

**Comment by Vargrey** [comment]
Not sure if TEdit3_BETA_v3.8.16218.129.zip were the one you meant, but it works.

**Comment by enigmaquip** [comment]
That would be the one! Excellent
