### ISSUE TITLE
Unhandled Exception ( Version 3.8.16227.0436 )

### ISSUE THREAD

**Issue by BunnyWarlord** [TEdit/Terraria-Map-Editor#878]
```
08-15-2016 01:06:42: Starting TEdit 3.8.16227.0436 
08-15-2016 01:06:42: OS: Microsoft Windows NT 6.2.9200.0 
08-15-2016 01:06:42: Failed to verify Terraria Paths. TEdit may not run properly. 
08-15-2016 01:06:42: Error - Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Configuration.XmlUtil..ctor(Stream stream, String name, Boolean readToFirstElement, ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile() 
08-15-2016 01:06:42: Error - Root element is missing. (C:\Users\User\AppData\Local\TEditXna\TEditXna.exe_Url_hq50c4uwwtzno320pd03qipox4kd5g5v\3.8.0.0\user.config)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e) 
08-15-2016 01:06:42: Error - Configuration system failed to initialize
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
   at System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(InternalConfigEventArgs e)
   at System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(String configPath, BaseConfigurationRecord configRecord)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   at System.Configuration.SettingsBase.get_Item(String propertyName)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at TEditXna.Properties.Settings.get_TerrariaPath() in c:\projects\terraria-map-editor\TEditXna\Properties\Settings.Designer.cs:line 31
   at TEditXna.DependencyChecker.CheckPaths() in c:\projects\terraria-map-editor\TEditXna\DependencyChecker.cs:line 17
   at TEditXna.App.OnStartup(StartupEventArgs e) in c:\projects\terraria-map-editor\TEditXna\App.xaml.cs:line 52 
08-15-2016 01:06:42: Unable to locate Terraria. No texture data will be available. 
08-15-2016 01:06:43: Error - Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Configuration.XmlUtil..ctor(Stream stream, String name, Boolean readToFirstElement, ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile() 
08-15-2016 01:06:43: Error - Root element is missing. (C:\Users\User\AppData\Local\TEditXna\TEditXna.exe_Url_hq50c4uwwtzno320pd03qipox4kd5g5v\3.8.0.0\user.config)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e) 
08-15-2016 01:06:43: Error - Configuration system failed to initialize
   at System.Configuration.ConfigurationManager.PrepareConfigSystem()
   at System.Configuration.ConfigurationManager.RefreshSection(String sectionName)
   at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   at System.Configuration.SettingsBase.get_Item(String propertyName)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at TEditXna.Properties.Settings.get_CheckUpdates() in c:\projects\terraria-map-editor\TEditXna\Properties\Settings.Designer.cs:line 55
   at TEditXna.ViewModel.WorldViewModel..ctor() in c:\projects\terraria-map-editor\TEditXna\ViewModel\WorldViewModel.cs:line 165
   at TEditXna.ViewModel.ViewModelLocator.CreateWorldViewModel() in c:\projects\terraria-map-editor\TEditXna\ViewModel\ViewModelLocator.cs:line 31
   at TEditXna.ViewModel.ViewModelLocator..cctor() in c:\projects\terraria-map-editor\TEditXna\ViewModel\ViewModelLocator.cs:line 13 
08-15-2016 01:06:43: Error - The type initializer for 'TEditXna.ViewModel.ViewModelLocator' threw an exception.
   at TEditXna.ViewModel.ViewModelLocator.get_WorldViewModel()
   at TEditXna.View.WorldRenderXna..ctor() in c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:line 71 
08-15-2016 01:06:43: Error - The invocation of the constructor on type 'TEditXna.View.WorldRenderXna' that matches the specified binding constraints threw an exception.
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at TEditXna.App.Main() in c:\projects\terraria-map-editor\TEditXna\obj\Release\App.g.cs:line 0 
```

**Comment by enigmaquip** [comment]
Try deleting the TEditXna directory here
C:\Users\User\AppData\Local\TEditXna
