### ISSUE TITLE
Terraria world corrupted and need help

### ISSUE THREAD

**Issue by Grandola** [TEdit/Terraria-Map-Editor#881]
08-15-2016 22:40:33: Starting TEdit 3.8.16227.0436 
08-15-2016 22:40:33: OS: Microsoft Windows NT 6.2.9200.0 
08-15-2016 22:40:34: Terraria Data Path: C:\Program Files (x86)\Steam\steamapps\common\Terraria\Content 
08-15-2016 22:40:34: Creating Undo cache: C:\Users\Cj\AppData\Roaming\TEdit\undo_907076363 
08-15-2016 22:44:47: Error - Object reference not set to an instance of an object.
   at TEditXna.View.WorldRenderXna.DrawSprites() in c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:line 457
   at TEditXna.View.WorldRenderXna.Render(GraphicsDeviceEventArgs e) in c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:line 367
   at TEditXna.View.WorldRenderXna.xnaViewport_RenderXna(Object sender, GraphicsDeviceEventArgs e) in c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:line 289
   at TEdit.UI.Xaml.XnaContentHost.GraphicsDeviceControl.CompositionTarget_Rendering(Object sender, EventArgs e) in c:\projects\terraria-map-editor\TEditXna\UI\Xaml\XnaContentHost\GraphicsDeviceControl.cs:line 325
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at TEditXna.App.Main() in c:\projects\terraria-map-editor\TEditXna\obj\Release\App.g.cs:line 0 

I tried to load my main world that was corrupted and this happened, there was no backup or previous versions so i came to TEdit to fix. Thanks for the help

**Comment by enigmaquip** [comment]
TEdit can't open a corrupt world file

**Comment by Grandola** [comment]
So if it cant be opened, is there any way to revive the file? There is no previous saves or backup

**Comment by enigmaquip** [comment]
No, a corrupted file does not have all the information in it needed to populate the world. It's a partial file

**Comment by Grandola** [comment]
Damn that sucks, thanks anyways :/
