### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Lampshade1234** [TEdit/Terraria-Map-Editor#896]
will watch  #751 all comments will be denied

```
09-12-2016 17:22:49: Starting TEdit 3.8.16253.2033 
09-12-2016 17:22:49: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
09-12-2016 17:22:49: Terraria Data Path: C:\Users\YUI\Desktop\IGG-Terraria.v1.3.2.1\Content 
09-12-2016 17:22:49: Creating Undo cache: C:\Users\YUI\AppData\Roaming\TEdit\undo_498411677 
09-12-2016 17:22:59: Failed to load texture: Images\Tiles_461 
09-12-2016 17:22:59: Could not load Images\Tiles_461 asset as a non-content file! 
09-12-2016 17:22:59: Failed to load texture: Images\Tiles_462 
09-12-2016 17:22:59: Could not load Images\Tiles_462 asset as a non-content file! 
09-12-2016 17:29:41: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateShaderResourceView(Resource resourceRef, Nullable`1 descRef, ShaderResourceView sRViewOut)
   at Microsoft.Xna.Framework.Graphics.Texture.GetShaderResourceView()
   at Microsoft.Xna.Framework.Graphics.TextureCollection.PlatformSetTextures(GraphicsDevice device)
   at Microsoft.Xna.Framework.Graphics.TextureCollection.SetTextures(GraphicsDevice device)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformApplyState(Boolean applyShaders)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.ApplyState(Boolean applyShaders)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformDrawUserIndexedPrimitives[T](PrimitiveType primitiveType, T[] vertexData, Int32 vertexOffset, Int32 numVertices, Int16[] indexData, Int32 indexOffset, Int32 primitiveCount, VertexDeclaration vertexDeclaration)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives[T](PrimitiveType primitiveType, T[] vertexData, Int32 vertexOffset, Int32 numVertices, Int16[] indexData, Int32 indexOffset, Int32 primitiveCount, VertexDeclaration vertexDeclaration)
   at Microsoft.Xna.Framework.Graphics.SpriteBatcher.FlushVertexArray(Int32 start, Int32 end, Effect effect, Texture texture)
   at Microsoft.Xna.Framework.Graphics.SpriteBatcher.DrawBatch(SpriteSortMode sortMode, Effect effect)
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.End()
   at TEditXna.View.WorldRenderXna.Render(GraphicsDeviceEventArgs e) in c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:line 381
   at TEditXna.View.WorldRenderXna.xnaViewport_RenderXna(Object sender, GraphicsDeviceEventArgs e) in c:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:line 289
   at TEdit.UI.Xaml.XnaContentHost.GraphicsDeviceControl.CompositionTarget_Rendering(Object sender, EventArgs e) in c:\projects\terraria-map-editor\TEditXna\UI\Xaml\XnaContentHost\GraphicsDeviceControl.cs:line 325
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at TEditXna.App.Main() in c:\projects\terraria-map-editor\TEditXna\obj\Release\App.g.cs:line 0 
```

**Comment by enigmaquip** [comment]
> 09-12-2016 17:22:59: Failed to load texture: Images\Tiles_461 
> 09-12-2016 17:22:59: Could not load Images\Tiles_461 asset as a non-content file! 
> 09-12-2016 17:22:59: Failed to load texture: Images\Tiles_462 
> 09-12-2016 17:22:59: Could not load Images\Tiles_462 asset as a non-content file! 

These are because it's trying to load assets from 1.3.3, you can try TEdit3_BETA_v3.8.16244.140.zip instead

> 09-12-2016 17:29:41: Error - HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
at SharpDX.Result.CheckError()

As stated when you submitted the issue

> **Before you submit an issue please read**
> If you get an unhandled exception, please check your log before posting
> If your log includes *DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved*
> This is a known issue, do not create a new issue, please add your comments to #751
> People have had the most luck in Windows 7 with updating to DirectX 11.1
> This is found in windows update in the optional updates section or by
> following directions here https://support.microsoft.com/en-us/kb/179113

There seems to be an issue in the latest version of monogame and certain video cards. The solution for most people has been making sure they're on DirectX 11.1 which is not an automatic update in Win 7. Also make sure you're video drivers are up to date. Some people have also had success with switching to using the integrated video instead of their GPU

**Comment by Lampshade1234** [comment]
umm 1 or 2

1: Windows6.1-KB2670838-x64.msu

2: Windows6.1-KB2670838-x86.msu

**Comment by enigmaquip** [comment]
x64 if you're running a 64 bit system, x86 if you're running a 32 bit system

**Comment by Lampshade1234** [comment]
it says that it is already on

**Comment by BinaryConstruct** [comment]
Ignore the warning, and install anyway. Uninstall if you must first.
