### ISSUE TITLE
TEdit 1.3.5.1 Error

### ISSUE THREAD

**Issue by Poot5** [TEdit/Terraria-Map-Editor#978]
I get this error when loading a 1.3.5.1 world with TEdit 1.3.5.1. How can I fix this? Thanks in advance.

04-23-2017 20:27:55: Starting TEdit 3.10.17110.2228 
04-23-2017 20:27:55: OS: Microsoft Windows NT 6.2.9200.0 
04-23-2017 20:28:01: Unable to locate Terraria. No texture data will be available. 
04-23-2017 20:28:01: Creating Undo cache: C:\Users\LeoDuduDavi\AppData\Roaming\TEdit\undo_717287701 
04-23-2017 20:28:09: Error - Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at TEditXna.View.WorldRenderXna.DrawNpcOverlay(NPC npc) in C:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:line 1875
   at TEditXna.View.WorldRenderXna.DrawPoints() in C:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:line 1818
   at TEditXna.View.WorldRenderXna.Render(GraphicsDeviceEventArgs e) in C:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:line 375
   at TEditXna.View.WorldRenderXna.xnaViewport_RenderXna(Object sender, GraphicsDeviceEventArgs e) in C:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:line 290
   at TEdit.UI.Xaml.XnaContentHost.GraphicsDeviceControl.CompositionTarget_Rendering(Object sender, EventArgs e) in C:\projects\terraria-map-editor\TEditXna\UI\Xaml\XnaContentHost\GraphicsDeviceControl.cs:line 329
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at TEditXna.App.Main()

**Comment by BinaryConstruct** [comment]
It looks similar to this issue: #976 , can you try the suggestion there?

**Comment by enigmaquip** [comment]
it's weird because the renderer shouldn't crap out until the map is zoomed in to a zoom level beyond the pixel rendering, unless I changed something without meaning to at some point... Ah no it's when it's trying to use the built in npc overlay's.... I guess we should update those for the new NPC's :-)

**Comment by Poot5** [comment]
I don't even understand that error. I tried to do whatever the hell did that say, and it STILL won't work.

**Comment by enigmaquip** [comment]
Should work now in the new version

**Comment by Poot5** [comment]
Thank you SO much! It's working flawlessly! Your program is great, too bad it can have errors...
Thanks again!
