### ISSUE TITLE
File keeps getting corrupted

### ISSUE THREAD

**Issue by Jameelioo** [TEdit/Terraria-Map-Editor#988]
Hey! So I was working on a build and all of a sudden my file has been corrupted? I tried loading a TEdit backup file and re-saving but it keeps getting corrupted. The software told me to post this in this section.

05-04-2017 23:10:12: Error - Object reference not set to an instance of an object.
   at TEditXna.ViewModel.WorldViewModel.MouseMoveTile(TileMouseState e) in C:\projects\terraria-map-editor\TEditXna\ViewModel\WorldViewModel.cs:line 856
   at TEditXna.View.WorldRenderXna.xnaViewport_HwndMouseMove(Object sender, HwndMouseEventArgs e) in C:\projects\terraria-map-editor\TEditXna\View\WorldRenderXna.xaml.cs:line 2066
   at TEdit.UI.Xaml.XnaContentHost.GraphicsDeviceControl.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in C:\projects\terraria-map-editor\TEditXna\UI\Xaml\XnaContentHost\GraphicsDeviceControl.cs:line 620

**Comment by Jameelioo** [comment]
[Build_Help.zip](https://github.com/TEdit/Terraria-Map-Editor/files/977366/Build_Help.zip)

**Comment by enigmaquip** [comment]
can you add the uncorrupted copy from your backup as well?

**Comment by Jameelioo** [comment]
[Build_Help.wld.20170504225225.TEdit.20170504231418.TEdit.20170504232236.zip](https://github.com/TEdit/Terraria-Map-Editor/files/978147/Build_Help.wld.20170504225225.TEdit.20170504231418.TEdit.20170504232236.zip)

Ths is the BAK file and also a TEdit autosave file before it got corrupted.

**Comment by Jameelioo** [comment]
The Software stopped corrupting my files. Not sure what fixed it but it's working now. However it is still a little laggy.
